### ISSUE TITLE
Modal capturing mouse - prevents selection

### ISSUE THREAD

**Issue by vron** [dnbexperience/eufemia#1104]
## 🐛 Bug Report

Hi,

After having been shown the first time and then hidden the Modal component seems to capture the mouse - at least it prevens selection of texct in e.g. p elements on the page after having been shown.

Rendering

`<Modal
                spacing={false}
                fullscreen={false}
                trigger_hidden={true}
                align_content="centered"
                hide_close_button
                prevent_close={true}
                max_width="22rem"
                open_state={metStore.calculation_in_flight}
            >
sadf
            </Modal>`

where calculation_in_flight starts as false, then it cahnging to true = > forces re-redner, then calculation_in_flight changes to false (hides the modal) leads to a state where the user cannot select text elsewhere on the page (althpugh clocking buttons etc. still works.

**Comment by vron** [comment]
Just let me know if anything here is not clear or you need more description

**Comment by vron** [comment]
@tujoworker is this soemthing you will have time to look at in the near future? It's currently a show-stopper for us.

Full respect for if it's not on your near term agenda - just let me know and we will for now render modals using some other package or see if I can look into it myself.

**Comment by tujoworker** [comment]
I will take a look on it today. Is it hard to reproduce?

**Comment by vron** [comment]
No, at leat here it re-produces every time - i can try to create a minimal example for you

**Comment by vron** [comment]
https://codesandbox.io/s/eufemia-input-masked-and-state-handling-forked-bbb0f?file=/src/App.tsx

**Comment by vron** [comment]
Note how the p element can be sleected before clicking the button - after the modal has once been rendered the text is no longer selecteable

**Comment by vron** [comment]
Thanks

**Comment by vron** [comment]
So I just updated to 9.16.1 and am still seeing the problem - does really the example i sent work for 9.16.1?

**Comment by vron** [comment]
FYI: No it doesnt: on https://codesandbox.io/s/eufemia-input-masked-and-state-handling-forked-bbb0f?file=/src/App.tsx when changing to 9.16.1 im still seeing the problem

**Comment by tujoworker** [comment]
Can you try a hard refresh with that version? I looks fine on my side 👍

**Comment by vron** [comment]
yeah - does here to when i now visit the link... Ok - guess i have some additional problem localy i need to figure out

**Comment by vron** [comment]
So I actually think the fix is not fully solving it - it 'sortof work" now but not fully, e.g.:

befor showing a modal i can select all items in a table by draging, copy and paste to excel.

After showing a modal that's not possible - though i can select the text in an "individual" cell in the table.

I can show you on teams if you want / this is unclear

**Comment by tujoworker** [comment]
I can't reproduce this right away. We may either cerate a reprod, or have a qick call – maybe tomorrow?

**Comment by vron** [comment]
Sure - just give me a call on teams tomorrow before 15

**Comment by tujoworker** [comment]
It should be reproduceable then I think?

**Comment by tujoworker** [comment]
Heres [one](https://codesandbox.io/s/eufemia-modal-selection-bug-79dul?file=/src/App.tsx) with a basic table.

**Comment by vron** [comment]
Indeed - i do not manage to easily re create it on my phone there at least - i also see there is a new release so will try the latest and report back monday whem at the pc

**Comment by vron** [comment]
So i can confirm that im still seeing this on the latest version (.3) locally - will try to creat a minimum example @tujoworker

**Comment by vron** [comment]
This one demonstrates it: https://codesandbox.io/s/eufemia-modal-selection-bug-forked-5fvb5?file=/src/App.tsx

Problem seems to arise when its "not rendered in a hidden state" - guessing the code then bypasses some clean up and leaves some event handler or what not lying around
