### ISSUE TITLE
InputMasked and del key

### ISSUE THREAD

**Issue by vron** [dnbexperience/eufemia#1113]
Hi,

I'm sorry - I keep reporting stuff I finde - hopefully it's usefull, if not just tell me to shut up :-)

So the input masked is working much better - but one small thing we notice:

If you have foprmated number in with with space sepperation, e.g 5 000 000:

If you now place the cursor just after the 5 (before the space) and press the [del] key on the keyboard nothing happens.

I would expect it to delete one 0 and re-format the number with spaces in the correct places.

(typicall occureswhen the user want to delete a lot of tailing numbers, will then "meet" a space sooner or later and not be able to delete further)

**Comment by tujoworker** [comment]
You very much have given good inputs in making components better. Please feel free to report everything! 💙

Now, to the issue you mention. Do I understand it correct, if I sum it like this; you want bothe the space and the nearest number to be removed?

**Comment by vron** [comment]
Hi,

Yes - since removing the space is nonsensical (would ruin formatting) the best option is removing both?

Vo

**Comment by tujoworker** [comment]
The behaviour like it is today, we do inherit, but we can change it as we like. 

Because the thousand separator is just a visual helper, and it would be put back again as soon as the user changes its value, we would actually have to "keep" the thousand separator char. This is how the Mobile Bank App is doing it. Can you check it out? Just start a new payment.

**Comment by vron** [comment]
Not sure what you want me to test - on my phone i do not have a "del" key. Backsapce works fine on both mobile on compter?

**Comment by tujoworker** [comment]
Sorry, I mean on the Mobile Bank (Native) iOS App – start a payment, and chek out the amount input.

**Comment by vron** [comment]
Im probably beeing stupid - but - i repeat what i wrote above - there is no “del” key on the phone? Backspace works fine

**Comment by tujoworker** [comment]
Yes, use the backspace there. And place the cursor on the other side.

**Comment by vron** [comment]
I think the following screencast shows the problem - starting at the "end" and using backspace works to remove all numbers - however if you start in the beggining / middle and use the "del" key we can't remove all the numbers - we get "stuck" at spaces

https://user-images.githubusercontent.com/160233/144805833-3129659d-7d5a-4cc3-a952-2c31deee2807.mp4
