### ISSUE TITLE
Tooltip: Disappears after a brief time with controlled `active` prop

### ISSUE THREAD

**Issue by dagerikhl** [dnbexperience/eufemia#1411]
## 🐛 Bug Report

When controlling a tooltip by setting the `active` property based on whether or not there is content for the tooltip, the tooltip sometimes disappears right after appearing.

In my application, I'm reliant on controlling the active prop.

It looks like the active prop is sent in correctly to the top-level Tooltip component, but somewhere down in the component tree it suddenly changes to `false`.

Did not have this problem in Eufemia v9.24.0, but I did have it in 9.26.0. I suspect this commit is the culprit: fb0fe332ee05c5ee6bee66b9b401106f96066b1f

Not sure if is also present in 9.25.0, but I expect so.

## To Reproduce

https://codesandbox.io/s/sharp-star-3x53k3

1. Try to hover the Button a couple of times.
2. Observe that sometimes (often), the tooltip disappears almost immediately after appearing.

## Expected behavior

The tooltip remains active, as the active prop sent to the Tooltip component is truthy.

## Run `npx envinfo`

Paste the results here:

```bash
  System:
    OS: Windows 7 6.1.7601
    CPU: (4) x64 Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz
    Memory: 17.73 GB / 32.00 GB
  Binaries:
    Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - C:\Program Files\nodejs\yarn.CMD
    npm: 6.14.12 - C:\Program Files\nodejs\npm.CMD
  Managers:
    Gradle: 6.6 - C:\Gradle\gradle-6.6\bin\gradle.BAT
    Maven: 3.6.3 - C:\Programs_Portable\apache-maven-3.6.3\bin\mvn.CMD
  Utilities:
    Git: 2.36.1. - /mingw64/bin/git
  IDEs:
    VSCode: 1.63.0 - C:\Users\ADXXXXX\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  Languages:
    Bash: 4.4.23 - C:\Program Files\Git\usr\bin\bash.EXE
    Java: javac 18 - /c/Program Files/Common Files/Oracle/Java/javapath/javac
    Perl: 5.34.0 - C:\Program Files\Git\usr\bin\perl.EXE
  Browsers:
    Internet Explorer: 11.0.9600.20296
```

## Eufemia Version

9.26.0

**Comment by dagerikhl** [comment]
Any news on this @tujoworker? :)

**Comment by tujoworker** [comment]
Yeah, sorry for the late reply! Will look into this tomorrow or early next week. Should not be a too large thing to fix + adding tests for it🤞 Just had a refactoring of the tests in this PR #1545 👍

**Comment by dagerikhl** [comment]
Super @tujoworker ! Looking forward to the fix :D

**Comment by tujoworker** [comment]
I guess your CSB code is fictive, right? I just wander, because the button also supports this:

```jsx
<Button tooltip="I am some tooltip">Text</Button>
```

**Comment by dagerikhl** [comment]
Yes, the CSB code is fictive. In my project I am using a custom React component as the target element.

This looks like a promising fix, thank you @tujoworker! 🙇

**Comment by dagerikhl** [comment]
Just tested this in a project with Eufemia v9.30.0, and the bug is unfortunately still present @tujoworker :(

**Comment by tujoworker** [comment]
@dagerikhl Can you try this version?

CLI run `npm i https://pkg.csb.dev/dnbexperience/eufemia/commit/c18b0212/@dnb/eufemia`

**Comment by dagerikhl** [comment]
I'm afraid that didn't go so well @tujoworker 😅 I got this error just when the tooltip is mounting (haven't even hovered anything yet):
```
Uncaught TypeError: Cannot read properties of null (reading 'getBoundingClientRect')
    at TooltipContainer.js:107:1
```

**Comment by tujoworker** [comment]
We should try to meet next week and look into it together. 

But could you try two things?

- ensure it's not a Babel/CRA issue
- update your fictive reproduction CSB with the new version and check is things are working as expected

**Comment by dagerikhl** [comment]
Hi @tujoworker ! Sorry for the late response, was not in office past week.

* I'm not sure exactly how I can verify it's not a Babel/CRA issue?
* Created a updated sandbox with v9.30.0, and I'm still seeing the issue there: https://codesandbox.io/s/elegant-christian-gj8nn7?file=/src/App.tsx
  * To reproduce: Move mouse fast out and back in on the button a couple of times. If you do it slowly it seems to work.

**Comment by tujoworker** [comment]
It should be fine now – try it out.

**Comment by dagerikhl** [comment]
This looks to be working since 9.31.0 🎉😁
