### ISSUE TITLE
Bug: Anchor contrast style icon

### ISSUE THREAD

**Issue by tujoworker** [dnbexperience/eufemia#1415]
ref.:
I Anchor för länk till extern sida (target="_blank") så går det inte att få ikonen vit om man använder contrast style för att texten ligger på mörk bakgrund. Sedan går det inte att ta bort underline med klassen för no-underline. 

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/1501870/169262047-f0542667-466f-450e-8f15-d9e19076b611.png)

**Comment by rozamoustafa** [comment]
This seems to be fixed 🎉
