### ISSUE TITLE
Stopwatch icon is corrupted

### ISSUE THREAD

**Issue by rodynenko** [dnbexperience/eufemia#1428]
## 🐛 Bug Report

Stopwatch icon is cut on the bottom.

## To Reproduce

https://codesandbox.io/s/eufemia-stopwatch-icon-is-corrupted-09fxgd (https://09fxgd.csb.app/)

## Expected behavior

Stopwatch icon should not be cut on the bottom, and looks like similar to Stopwatch medium icon

## Eufemia Version

v. 9.26.0, v. 9.25.0

Previous OK version 9.24.0 
https://codesandbox.io/s/eufemia-stopwatch-icon-is-not-corrupted-v9-24-9cy5v9?file=/src/App.tsx

**Comment by tujoworker** [comment]
Thank you @rodynenko and @langz  ❤️
