### ISSUE TITLE
Cookie modal issue when using adblockers

### ISSUE THREAD

**Issue by lherlanddnb** [dnbexperience/eufemia#1431]
When visiting a page using Eufemia the cookie modal is not showing when using a browser with AdBlockers like AdBlock plus, Ghostery etc.

It creates a shaded dark look indicating a modal is present, but it is not showing on screen. This renders the page unusable since you cannot click anything. If you click ESC on the keyboard, then the "shaded" look will disappear and make the page usable, until you click on a new page.

This can be tested on https://dnbeiendom.no by using Chrome + Ghostery or Firefox + Ghostery.

**Comment by tujoworker** [comment]
Hi, thank you for reporting this issue.

I could replicate this by using Ghostery on dnbeiendom.no, but I could not replicate it on the original implementation. 

https://eufemia.dnb.no/uilib/components/dialog

This needs to get reported to the dev team working with that. I will at least provide them with this issue. Lets hope they could look at tit.
