### ISSUE TITLE
Let Autocomplete's options use the full width, before it breaks to a new line

### ISSUE THREAD

**Issue by langz** [dnbexperience/eufemia#1531]
It would be awesome if Autocomplete's options could use the full width in the drawer before breaking into a new line.

Attached is a screenshot from a form I'm making where we use Autocomplete to help the user to select country code for a phone number:

<img width="154" alt="image" src="https://user-images.githubusercontent.com/1359205/186660909-8bf95e97-928a-4690-9b38-b862583b9c39.png">

It's clearly more space available on the right side, not sure why it's not available for use 🤔 

I think the reason for it to "break early" is something something related to https://github.com/dnbexperience/eufemia/blob/fe6fbb73fdba4ebf2166710d6ff48bfba36a5876/packages/dnb-eufemia/src/fragments/drawer-list/style/_drawer-list.scss#L179

Here's a screenshot of the same example, when I just remove the line of styling above:

<img width="164" alt="image" src="https://user-images.githubusercontent.com/1359205/186661223-d1d0b42f-d3b3-4999-aa37-e2ce24424c52.png">

An other example of when it doesn't "use the full width" can also be seen in the docs, https://eufemia.dnb.no/uilib/components/autocomplete/demos/#custom-width, pressing the top autocomplete example, the option "The Godfather" could have enough space to not wrap the text "The Godfather" over two lines.

<img width="363" alt="image" src="https://user-images.githubusercontent.com/1359205/186662694-474eea93-f433-417c-83d1-b0d254dbf42a.png">

**Comment by tujoworker** [comment]
Yeah, maybe it would be good to just use that extra space, when the `checkmark` is shown? Here is a screenshot with the checkmark. But when its not selected, we could free up the space 🤔

<img width="291" alt="Screenshot 2022-08-26 at 15 27 35" src="https://user-images.githubusercontent.com/1501870/186914298-2f4a5f65-f2c2-4f52-bcf8-33761c32e0e1.png">

**Comment by langz** [comment]
Aha, so that's what the line of code is used for 👍 
Yeah, something along those lines would be awesome. Like if it only contain text, and no icons, use the full width or so.
