### ISSUE TITLE
Should it be an underline under the badge when hovering our links in the portal's menu?

### ISSUE THREAD

**Issue by langz** [dnbexperience/eufemia#1989]
This is how it is locally on my machine now, in the v10 branch:
Video:
https://user-images.githubusercontent.com/1359205/218488201-96e3309a-7780-4caa-a7cc-fa53bd6a1ff9.mov
Screenshot:
<img width="548" alt="image" src="https://user-images.githubusercontent.com/1359205/218489792-f811e358-e901-4366-bee1-40a153e168d3.png">

It wasn't like this before, when we used a different type of badge, then it didn't have an underline under the badge when hovering:
Video:
https://user-images.githubusercontent.com/1359205/218488568-5ca09118-73e7-4468-a730-43b9631a6f55.mov
Screenshot:
<img width="460" alt="image" src="https://user-images.githubusercontent.com/1359205/218489886-8a5afc49-aa6c-4a6a-a333-c3b7c88ff9a7.png">

I'm not sure what's the best and appropriate solution here, just reporting my observation for now 🙏

**Comment by tujoworker** [comment]
Ohh, nice finding. No, the underline should not be visible. I think we should fix that in the component itself, if possible.
