### ISSUE TITLE
Input masked not accepting leading 0s

### ISSUE THREAD

**Issue by vron** [dnbexperience/eufemia#1999]
Go to https://eufemia.dnb.no/uilib/components/input-masked/ and test e.g. the " Number (decimal limit)" example:

I have two issues:

1. It's imposiblle to e.g enter 0.01 since it seems to ignore the second 0
2. It's very hard to add the first 0 - e.g. if you select all the contents and press 0 on the keyboard nothing happends

**Comment by tujoworker** [comment]
Hi!

Thanks for getting in touch with your findings 🙏 I think both cases are taken care of in the upcoming v10

1. In [v10 we default](https://github.com/dnbexperience/eufemia/pull/1126) to allow a leading zero (`mask_options={{ allowLeadingZeroes: true }}`). The same example looks to work fine in a [random v10 build](https://eufemia-featskipcontenthelper.gatsbyjs.io/uilib/components/input-masked/).
2. Is probably the same as 1.

I will close this as solved. But feel free to open it again if you think there is more we should align 🙏
