### ISSUE TITLE
UI: Switch: Sliding not working

### ISSUE THREAD

**Issue by vron** [dnbexperience/eufemia#201]
## 🐛 Bug Report

The Switch component does not behave as users expect. 3/4 users who have tested my UI (built on eufemia) have tried to "slide" ("click-drag-release") the component instead of simply clicking it. After trying to slide and failing they did manage to click, regardless i think the component should support the behaviour many users first assume when encountering it.

Ie., in addition to "click to change" it shoudl support "slide to change" - makes sense as it is rendered as a slider.

## To Reproduce

<Switch />

## Expected behavior

see above

**Comment by tujoworker** [comment]
Thank You @vron for Your god explained and derailed request. 
I agree with You and will add it to a feature list!

**Comment by tujoworker** [comment]
This should work now as decribed. Feel free to open up this issue if it does not. Thanks again 💙

**Comment by vron** [comment]
Nice,

Good to see even old issues being picked up :-)
