### ISSUE TITLE
UI: Tabs and scrolling of content

### ISSUE THREAD

**Issue by vron** [dnbexperience/eufemia#202]
## 🐛 Bug Report

The Tabs component works well to render a ui for eg a multistep form. However, when the content rendered in the tab is long (overflowing page) the scrollTop position will be remembered by the browser, such that the user journey becomes:

1. User fills out first step of form, scrolling downwards.
2. When at bottom clicks a "next" button.
3. Next step is rendered, but instead of starting at top of step2 he/she will start scrolled down to the bottom of step 2. (which confuses users)

To my understandimg this is the type of scenario it is intended for? I am working around this now by attaching an event handler and setting scrollTop - but maybe the component should handle that itself?

## To Reproduce

i think the above is clear, if not let me know and i can provide code.

## Expected behavior

see above

**Comment by tujoworker** [comment]
Speaking of fixing old issues, in v7.2.4 also an optional `scroll={true}` property is given, that solves this request 🎉
