### ISSUE TITLE
Console errors in Pagination example/demo "Centered Pagination with random delay"

### ISSUE THREAD

**Issue by langz** [dnbexperience/eufemia#2029]
## 🐛 Bug Report

When running the Pagination example/demo "Centered Pagination with random delay" locally, I get an error in the console.
Not sure if this issue highlights an error in the example or in the component itself, so it could be worth a quick "deep dive" to figure out. 

I also think/would guess that it should display 1 and not no number on first load.
i. e display 
<img width="934" alt="Screenshot 2023-02-28 at 14 35 31" src="https://user-images.githubusercontent.com/1359205/221869729-fd9ddc01-92c6-4e3f-b3b8-c678cced906f.png">
 instead of displaying (which it does now): 
<img width="934" alt="Screenshot 2023-02-28 at 14 35 40" src="https://user-images.githubusercontent.com/1359205/221869797-0df1562f-7262-4879-bb5f-34a59e8bf454.png">

## To Reproduce

Run the [following example](https://eufemia.dnb.no/uilib/components/pagination/#centered-pagination-with-random-delay) locally in the v10 branch, I get the following error:

<img width="2560" alt="image" src="https://user-images.githubusercontent.com/1359205/221868634-5c4b38e1-eaca-470f-ba39-1d1ca2d5e75d.png">

Error in text:
```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    at PaginationProvider (webpack-internal:///../dnb-eufemia/src/components/pagination/PaginationProvider.js:105:34)
    at Pagination (webpack-internal:///../dnb-eufemia/src/components/pagination/Pagination.js:141:33)
    at ErrorBoundary (webpack-internal:///../../tools/react-live-ssr/index.js:594:25)
```

**Comment by tujoworker** [comment]
I could not reproduce it. I think it may have been solved by last weekends update of [this dependency](https://github.com/dnbexperience/babel-plugin-react-live/releases).
