### ISSUE TITLE
FormLabel direction prop, is it a real prop or not?

### ISSUE THREAD

**Issue by langz** [dnbexperience/eufemia#2055]
In the documentation, we refer to the direction prop of FormLabel(https://eufemia.dnb.no/uilib/components/form-label/properties/), but I'm not able to see any more info about the property in the properties docs...

<img width="2559" alt="image" src="https://user-images.githubusercontent.com/1359205/223386073-da8912fd-d156-4fc4-846d-5e4401125523.png">

**Comment by tujoworker** [comment]
No, not the FormLabel, but FormRow. Looks like its a blind copy&paste 😝
