### ISSUE TITLE
Input (and masked Input)

### ISSUE THREAD

**Issue by vron** [dnbexperience/eufemia#209]
Depending in the use case and the expected user behaviour two different modes makes sense to have for input boxes:

1. The "As is behaviour" where a click will place a cursor at the particular location in the string where the user clicked. This typically makes sense for initially empty boxes where editing or adjustment is expected.

2. The "Excel" or "URL bar" behaviour where one click initially selects everything such that the user can "click and type" to add a new value. This typically makes sense for several use cases where small nubers are to be entered in multiple boxes, e.g. percentages or similar. (Note that this is the behaviour you get if you use tab to cycle through, but we find many, in particular not-as-young users prefer to use the mouse to select the next box. A second click should now place the cursor at the location?

Maybe this could be a property on the component that toggles this mode? Something like "urlmode" or "selectall"?

**Comment by tujoworker** [comment]
`selectall` is now supported as a prop in [v3.31.0](https://github.com/dnbexperience/eufemia/releases/tag/v3.31.0)
