### ISSUE TITLE
Dropdown Not updating

### ISSUE THREAD

**Issue by vron** [dnbexperience/eufemia#211]
Maybe a bit of an edge case, but one I would expect the Dropdown component to handle:

Short description: Have a UI where the user needs to select X items out of Y options. The Y options are displayed in a dropdown, and when one is selected in the dropdown an additional icon will be displayed illustrating that the option has been selected.

Critically however I would then, for Easy of use for the user, want to remove the corresponding item from the dropdown (each item can only be selected once), so as to not confuse the user.

This seems not to work however, due to the way the Dropdown component is implemented, when selecting an item from the list the internal field _listenForPropChanges (in getDerivedStateFromProps) seems to be set to false, thus preventing a re-rendering, and this preventing the removal of my options from the data property (note that I am sending a new [...array]., not just modifying it in place.)

I.e. changing line 168 in https://github.com/dnbexperience/eufemia/blob/develop/packages/dnb-ui-lib/src/components/dropdown/Dropdown.js to:

    if (true)

makes it work as I would expect - but Im not sufficiently into this code to see if that could have other bad consequences (apart from obviously slightly worse performance).

**Comment by vron** [comment]
Please let me know fi the above is not clear, note that I for now seem to be able to work around it by the modification i mention above.

**Comment by tujoworker** [comment]
Hi Viktor! Thanks for dropping by with this issue: Have a look at [this demo](https://codesandbox.io/embed/eufemia-dropdown-rby1t)

Is this You want to achieve?

**Comment by vron** [comment]
No, I dont think so (but not sure), I think that example is "cheating" by only reacting on the button clicks. What I want is "direct reaction" when the value in the dropdown is changed.

E.g. see the following example that to my understanding "does not work as expected": 

https://codesandbox.io/embed/eufemia-dropdown-oo4mj

**Comment by vron** [comment]
I.e., to my understanding the above example illustrated that the Dropdown does not fully behave as I would normally expect a React component to, which is to always re-render to match the properties it is beeing sent/updated with - it simply ignores that the data property has changed and uses the old/cached one instead.

**Comment by tujoworker** [comment]
Sorry, I'm on parental leave last and this week, so slow responses from my side.

I will make some changes to that, but keep in mind, `getDerivedStateFromProps` gets not "triggered" if we send in the same *array* instance. It has to be a new instance to trigger a rerender.

But for sure, You **have** send in a new instance, so this has to be fixed!

**Comment by tujoworker** [comment]
#213 will fix this - let me know if it worked out for You.

**Comment by tujoworker** [comment]
If I delay the `setState` in the **selectItem** methode inside the #dropdown component - then it would work.
So #214 will fix this issue.

**Comment by vron** [comment]
No problem at all, enjoy that time!

This solves my problem, confirmed.
