### ISSUE TITLE
Dropdown to support custom content

### ISSUE THREAD

**Issue by vron** [dnbexperience/eufemia#216]
Currently the dropdown is rather smart, handling the content, multiplines etc. However, in some cases it may be desirable to add custom content to e.g. display an icon or other custom content, i.e.:

    const data = ["SEK", "NOK", "USD"].map(c => ({
        selected_value: c,
        content: <span><Flag land={c} />{c}</span>,
    }))

Today this almost works (it actually does work in that it renders correctly), but the propCheck throws an error on the type of the content field.

**Comment by vron** [comment]
example:

https://codesandbox.io/embed/eufemia-dropdown-oo4mj

However, seems not to give any warnigns in the console - maybe React only shows this warnings in development mode (which is why i see it locally) and not when build for prod?

**Comment by vron** [comment]
Seems like I pasted the wrong link above, should be this one:

https://codesandbox.io/embed/eufemia-dropdown-rc4dg

**Comment by tujoworker** [comment]
Yeah, the `data` structure is now mutch more flexible and should support custom components without this dev warning.
