### ISSUE TITLE
Should we remove the React.Fragments (<>) in our examples/docs?

### ISSUE THREAD

**Issue by langz** [dnbexperience/eufemia#2172]
## 🐛 Bug Report

Related to #2007

In v10 we display a lot more React.Fragments(`<>`) in our examples than what we did in v9:

<img width="2560" alt="Screenshot 2023-03-30 at 12 01 23" src="https://user-images.githubusercontent.com/1359205/228804010-dff00555-4353-4aa0-84f4-bbf7e7ba22b4.png">

As part of v10  #2007 we refactored our examples from `.md` and `.jsx` to `.tsx`. In that process we changed our examples from:

```
<ComponentBox>
{`
<P>Hello World</P>
<P>Hello World</P>
`}
</ComponentBox>
```

To:

```
<ComponentBox>
   <P>Hello World</P>
   <P>Hello World</P>
</ComponentBox>
```

This leads to React(?) automatically wrapping the `<P>`'s in a React.Fragment `<>`, so the output of the example in our docs(LiveCode) will look like:

```
<>
   <P>Hello World</P>
   <P>Hello World</P>
</>
```

Previously in v9, it would look like:
```
<P>Hello World</P>
<P>Hello World</P>
```

Following is one of many many example in v10 today:
<img width="2560" alt="Screenshot 2023-03-30 at 12 01 23" src="https://user-images.githubusercontent.com/1359205/228804010-dff00555-4353-4aa0-84f4-bbf7e7ba22b4.png">

## To Reproduce

Take a look at one of the many examples in v10s portal/docs.

## Expected behavior

Should we just keep it as it is in v10 or try to somehow fix this, to make it look more like it did in v9?
Following is a screenshot from v9:
<img width="2560" alt="Screenshot 2023-03-30 at 12 00 54" src="https://user-images.githubusercontent.com/1359205/228804211-a87f8318-99c7-4715-8785-e924ee177528.png">

## Thoughts

I don't think it's a possible solution to wrap each example as done in v9, as we'll lose TS-functionality I believe:
```
  <ComponentBox>
    {
      /* jsx */ `
<P>Hello World</P>
`
    }
  </ComponentBox>
```

**Comment by langz** [comment]
This is nothing critical, I just wanted to inform/share this "discovery". We might not even want to fix this small issue at all.

**Comment by tujoworker** [comment]
I agree! Its unnecessary.
