### ISSUE TITLE
Fix Card complaint demo

### ISSUE THREAD

**Issue by langz** [dnbexperience/eufemia#2174]
## 🐛 Bug Report

Should we fix "Card complaint demo" before release of v10?
Are all the changes(marked in red) intentional, or not? 
If they are "breaking" for our demo app, it might be breaking for other apps that use eufemia as well 🤔 
I couldn't find info in `v10-info.mdx` about `Tabs` having breaking changes, but it will probably be generated documentation of this based on a commit containing "breaking change:" or so, I guess/hope.

<img width="2560" alt="image" src="https://user-images.githubusercontent.com/1359205/228838308-2a87f440-f31e-4d07-ae2c-5d20fd54857c.png">

**Comment by tujoworker** [comment]
Interesting and good you found this. Could have to do with the FormRow changes lately. We should find out whats causing this, before v10 release.
