### ISSUE TITLE
Scrolling in dropdown not working

### ISSUE THREAD

**Issue by vron** [dnbexperience/eufemia#218]
A Dropdown component with many elements will not scroll as expected in chrome on windows when using the mouse.

To Reproduce:

 1. Render a dropdown with many enough options to cause scrolling to be needed.
 2. On windows (opposite to e.g. osX) a scrollbar will then be rendered in the dropdown
 3. Scrolling up and down using the mouse wheel works now, but:
 4. Clicking and drawing the scrollbar to move it causes the dropdown to close instead, such that it's difficult to select non visible items if one has no wheel on the mouse.

I assume this is because mousedown or something similar is being handled.

**Comment by vron** [comment]
Note that the above is on a win7 machine, Im not sure windows 10 behaves the same with the scrollbar

**Comment by tujoworker** [comment]
Thanks for the request! Scroll should now work fine in v3.31.0 - can You confirm?

**Comment by vron** [comment]
@vaccation but will check when back
