### ISSUE TITLE
Clear Autocomplete's value using the enter key

### ISSUE THREAD

**Issue by langz** [dnbexperience/eufemia#2185]
## 🐛 Bug Report

Should it be possible to clear the `Autocomplete`'s value using the enter key? 
Or is this maybe not an expected functionality?

As of now, I'm not able clear the `Autocomplete` using the enter key:

https://user-images.githubusercontent.com/1359205/229106021-dccc0a71-b825-4579-8ede-32bf9c3cd93f.mov

## To Reproduce

Test tabbing and pressing enter when the "clear button/icon" is active: https://eufemia.dnb.no/uilib/components/autocomplete/demos/#autocomplete-with-numbers

**Comment by tujoworker** [comment]
Yes, looks like a bug! Thanks for reporting 🙏
