### ISSUE TITLE
DatePicker shortcut behavior

### ISSUE THREAD

**Issue by joakbjerk** [dnbexperience/eufemia#2189]
## 🐛 Bug Report

When selecting multiple shortcuts in the DatePicker, the selected styling will persists until the user clicks on the shortcut agian, giving the impression that the shorctus are multiple select, instead of toggleable. Is this the intended result? If not, then maybe we should remove the active styling from the last shortcut, when a new one is selected?

https://user-images.githubusercontent.com/25927156/229822449-97af7272-edfb-4c33-9279-e43dc8d1d4ce.mov

## To Reproduce

Go to the [Codesandbox](
https://codesandbox.io/s/ancient-fog-t8z0yn?file=/src/App.tsx) and select multiple shortcuts at the same time

**Comment by tujoworker** [comment]
Yes, I agree, we should probably just swap out the usage of ToggleButtons with a regular button.
