### ISSUE TITLE
InputMasked not updating when mask updated

### ISSUE THREAD

**Issue by vron** [dnbexperience/eufemia#219]
The InputMasked component does not re-render when the mask is updated (making it impossible to dynamically update the prefix?)

Please see the following example: 

https://codesandbox.io/embed/eufemia-dropdown-9dy6l

**Comment by vron** [comment]
(Where to be clear, the prefix in the rightmost input would be expected to change when the currency is changed in the dropdown)

**Comment by tujoworker** [comment]
This issue as also been fixed and should work: https://codesandbox.io/s/eufemia-dropdown-dox03
