### ISSUE TITLE
Copy from NumberFormat

### ISSUE THREAD

**Issue by vron** [dnbexperience/eufemia#2238]
## 🐛 Bug Report

Hi, when copying values from a number format and pasting into another application (e.g. outlook) the resulting formatting is bad. I assume this being a problem only in application where it is html that is pasted and not raw text - but ufortunately a case we find our users tries to do quite often.

## To Reproduce

1. Go to https://eufemia.dnb.no/uilib/components/number-format/demos/
2. Select the rendered demos and Ctrl-C:
![image](https://user-images.githubusercontent.com/160233/233265851-aad247a7-a6e3-4181-b8a8-1d8cb25cafc8.png)

3. Paste the copied content into e.g. Microsoft outlook and compare the result (all numbers are shown 3 times!)
![image](https://user-images.githubusercontent.com/160233/233266029-78b04879-bbee-4226-a969-32868a719f39.png)

## Expected behavior

I understand that outlook has a bad html rendering engine so we do not expact all styles to match perfectly - I would however expect each number only to be rendered / showed once.

```

## Eufemia Version
Latest

**Comment by tujoworker** [comment]
Thank you for submitting your issue 🙏

I just want to give the issue some more context.

- It only happens on blink (chromium) based browsers, such as Edge.
- Firefox and Safari does not have this negative effect.
- The reason behind it, is to make numbers more accessible to screen readers and the select&copy&paste feature. 

That said, we can use different approaches to solve the issue. 
If you are willing to use `copy_selection={false}`, either via a global Provider, or directly on the component, we can solve the rest with some tricks. 
I will open a PR.

**Comment by tujoworker** [comment]
You can visit [this build](https://eufemia-git-fix-number-format-copy-paste-eufemia.vercel.app/uilib/components/number-format/demos/) and edit the code  to include `copy_selection={false}` and it should now be clean when pasting from Edge to Outlook.

<img width="431" alt="Screenshot 2023-04-20 at 12 15 48" src="https://user-images.githubusercontent.com/1501870/233336659-1f79c3d2-347c-4765-bc5b-43ec255b2c1c.png">

The PR will go into v10 of Eufemia, which will be released very soon.

**Comment by vron** [comment]
Nice - looking forward to upgrade then once it's out :-)

**Comment by tujoworker** [comment]
I'm out on a run 🏃‍♂️ but had an idea, which may make it possible without the deactivation of the copy feature 💫🏃‍♂️

**Comment by tujoworker** [comment]
Looks like it works! Here are the [latest changes](https://github.com/dnbexperience/eufemia/pull/2240/commits/4b6069f13a9c71a07858ce0ea0b032a9430b6cad).

You may check out the preview, once the [build](https://github.com/dnbexperience/eufemia/pull/2240#issuecomment-1516057271) has finished.
