### ISSUE TITLE
Certain links in our documentation doesn't work in v10 anymore

### ISSUE THREAD

**Issue by langz** [dnbexperience/eufemia#2286]
## 🐛 Bug Report

Certain links in our docs doesn't seem to work properly anymore as part of v10.

One example is the following link to `/uilib/helpers/tools/#code-editor-extensions`:
<img width="2560" alt="Screenshot 2023-05-05 at 13 46 01" src="https://user-images.githubusercontent.com/1359205/236449658-ceebf97f-dcc7-4cc6-b8a1-a1ca05ca5f5e.png">

They do however work in v9 / what's deployed to https://eufemia.dnb.no/uilib/getting-started/

Initially I'm not sure what's causing this, hence me reporting it instead of fixing it.

**Comment by tujoworker** [comment]
Locally in dev mode? or on a build?

**Comment by langz** [comment]
Both.
See the following deploy preview: https://eufemia-git-chore-minor-text-updates-eufemia.vercel.app/uilib/getting-started/

**Comment by tujoworker** [comment]
I work on a fix. Just need to complete writing test...
