### ISSUE TITLE
How to link to docs of specific brand/theme?

### ISSUE THREAD

**Issue by langz** [dnbexperience/eufemia#2374]
## 🚀 Feature Proposal

I would like to link the docs of a given component in a given brand/theme to other designers and devs. Sending a link like: https://eufemia.dnb.no/uilib/components/badge/demos?theme=dnbeiendom
Let's say that a designer is wondering how the anchor looks for brand/theme DNB Eiendom, I would want to be able to link it to him.

As of today, the person receiving the link would have to know to right click the "three dots" in the top right corner and "click change style theme" and select the correct theme.

Potential possible ways of solving this:
- Using a query param?
- When in the portal, we could a query param to the URL when user changes to any theme other than the default theme, so that the user quickly can copy the URL displayed in his browser's address bar and share it with his friends.

**Comment by tujoworker** [comment]
This is possible 👍 we need to update the docs and mention the possibilities.
