### ISSUE TITLE
NumberFormat suffix adds extra space

### ISSUE THREAD

**Issue by mbacherycz** [dnbexperience/eufemia#2541]
## 🐛 Bug Report

In Eufemias [documentation](https://eufemia.dnb.no/uilib/components/number-format/properties/) on NumberFormat component, suffix should be added after the number including whitespace. The space is added also when providing a string without spaces.

CodeSandbox:
https://codesandbox.io/s/eufemia-starter-forked-s2jylk?file=/src/App.tsx

**Comment by tujoworker** [comment]
Hi! Thanks for reporting your thoughts/issue. Let's have a chat on Slack about this, first.
