### ISSUE TITLE
Add Lead to docs/portal?

### ISSUE THREAD

**Issue by langz** [dnbexperience/eufemia#2650]
## 🚀 Feature Proposal

Should we add info about `Lead` component to docs.
It looks to be a component/element that we expose to our users, https://codesandbox.io/s/crazy-pond-g9pdm6?file=/src/App.tsx

## Motivation

We show usage of the `Lead` component in https://eufemia.dnb.no/uilib/typography/#typography-examples, but we don't have a designated docs page for the `Lead` component in HTML Elements docs https://eufemia.dnb.no/uilib/elements/

**Comment by tujoworker** [comment]
Yes, I think so too.

**Comment by langz** [comment]
I can take a look at it, and add it to the docs.
Should we add it [/elements](https://eufemia.dnb.no/uilib/elements/) or [/components](https://eufemia.dnb.no/uilib/components/) ?

**Comment by tujoworker** [comment]
I would add it to elements.
