### ISSUE TITLE
Searching provides multiple and erroneous search results

### ISSUE THREAD

**Issue by langz** [dnbexperience/eufemia#2691]
## 🐛 Bug Report

When trying to use the search field in Eufemia, I get multiple search hits for the same "result" where a few of the results are erroneous(linking to a page that doesn't exist).

This seems to mostly happen when searching for words that are part of the "forms extension".

## To Reproduce

Go to: https://eufemia.dnb.no/, and try searching for "Button" or "PhoneNumber".

See the result when searching on "PhoneNumber":

https://github.com/dnbexperience/eufemia/assets/1359205/c0af4948-ed51-488e-ae80-86997ae570ea

**Comment by tujoworker** [comment]
The reasons is that we move lastly around things without adding a redirect directive (even I never checked if Algolia actually takes this into account).
 
We can bust the index before next release.
