### ISSUE TITLE
Search result text overflow

### ISSUE THREAD

**Issue by tariknh** [dnbexperience/eufemia#2698]
## 🐛 Bug Report

When searching for e.g button, the drawer displays the overflow with a horizontal scrollbar

## To Reproduce

Search for button

https://github.com/dnbexperience/eufemia/assets/112902780/f8862c55-dca6-41f2-9549-3064b645d98b

🍀 Use [this starter](https://eufemia.dnb.no/issue) to reproduce the issue.

## Expected behavior

Expected the text to wrap

## Fix

I solved it by removing "white-space: nowrap;" for the .dnb-drawer-list__option__item .dnb-anchor css tag
I can happily do a pull request on this

![image](https://github.com/dnbexperience/eufemia/assets/112902780/2e62eac4-eca6-438f-b0d5-ff16d27b51a6)

**Comment by tujoworker** [comment]
Thank you for the very good report about this issue 🙏 Here's a [quick PR](https://github.com/dnbexperience/eufemia/pull/2700) that also includes a visual regression test on this issue.
