### ISSUE TITLE
Autocomplete not firing on_change in async

### ISSUE THREAD

**Issue by vron** [dnbexperience/eufemia#2847]
When using Autocomplete in async mode, where the options returned by the async function **differ** between different calls (in our use case the string the user searches for is first filtered on the server - since the options are so many) the component will not trigger when there is only one option available. We have several users being tricked by this - thinking they gave changed the option but not being registered since on_change is not called.

In particular we notice this when there is only 1 option available:

1. The user types something in the autocomplete box
2. This triggers a async call to the `on_type` handler
3. Since the entry typed by the user is so specific only one option is available, so the `on_type` handler calls `updateData([{selectedKey: "entry1", content: "Entry 1"}])`
4. The user selects "Entry 1"
5. `on_change` is successfully called
6. A while later the user types in the autocomplete again, again something very specific
7. Again, only one option is available so `on_type` calls `updateData([{selectedKey: "Specific1", content. "Specific 1"}])`
8. The user clicks the (only available) entry "Specific 1"
9. **Critically** `on_change` is Not called (only `on_hide`) => mismatch between what the user has selected and registered.

The *same* problem occurs if the user at point 6, 7, 8 types something where the area multiple options available but clicks the first one.

It seems to me that the code is incorrectly detecting a "change" using a index based lookup (i.e. is it still the first item) instead of checking the key - a logic that works for static lists but not whit the async callback functionality (which is a critical part of the autocomplete functionality).

@tujoworker is this something  you could either consider a point release for or suggest some workarounds? (I have tried various ways to work around but nothing working consistently and thus creating problems for our users)

**Comment by langz** [comment]
Thanks for the report @vron 🙇 
I've tried transforming your detailed description into a [code example](https://codesandbox.io/s/hopeful-monad-hgc6vx?file=/src/App.tsx), and I think I've managed to do so 🤔 
Could you please take a look at the following [CSB](https://codesandbox.io/s/hopeful-monad-hgc6vx?file=/src/App.tsx), and see if I've managed to capture the essence of the reported issue in the [CSB](https://codesandbox.io/s/hopeful-monad-hgc6vx?file=/src/App.tsx).

**Comment by vron** [comment]
Indeed - that captures the problem I have noticed

**Comment by langz** [comment]
Great, thanks 🥇
