### ISSUE TITLE
Autocomplete sometimes keep selected item when not making a selection, other times not.

### ISSUE THREAD

**Issue by langz** [dnbexperience/eufemia#2876]
## 🐛 Bug Report

[CSB](https://codesandbox.io/s/eloquent-brown-cgdd8t)

I as a user did think that _**my selected value would always be kept until I select a new one**_(this expectation is just based on how our Autocomplete works, step 1 to 4). But sometimes it does, and sometimes it does not, like in the following scenario:
1. User types `"A"`
2. User selects `"AAA"`
3. User types `"something"` or `"c"`
4. User presses outside of the autocomplete(on blur) and the selected value is still `"AAA"` as expected.
5. User types `"b"`
6. User presses outside of the autocomplete(on blur) and the selected value is now `empty`.

I feel like as a user, that these two actions(type/search and press outside, while having a selected item) should result in the same result(still having the selected item).

Here's a video of the scenario described:

https://github.com/dnbexperience/eufemia/assets/1359205/2cf08878-a13a-4c77-ba8b-f0d2065f8b65

This issues is based on the comment from here https://github.com/dnbexperience/eufemia/pull/2865#pullrequestreview-1722666568

**Comment by tujoworker** [comment]
Closing this issue, as discussed in Slack, we can't do anything more than "removing" the selection, when a new data-set was given, where the selected key does not match anymore.
