### ISSUE TITLE
Add "Unknown" status to PaymentCard 

### ISSUE THREAD

**Issue by dsa015** [dnbexperience/eufemia#2933]
Back again 👍 proposing to add an extra card_status called "Unknown", as some of the incoming cards can have an unknown status state. Therefore we want to add this to the status lineup so that cards with this state can get the Blocking overlay aswell.

Found this from the api as this is a possible status state, that I forgot add together aswell.

**Comment by langz** [comment]
Thanks for reporting this feature request @dsa015 
I've created a quick PR now, https://github.com/dnbexperience/eufemia/pull/2934

Could you take a look at it, and add your thoughts to the text used, if we should have a icon or not(if so, which icon?), and general functionality? 🙏
