### ISSUE TITLE
DatePicker not respecting initial date

### ISSUE THREAD

**Issue by vron** [dnbexperience/eufemia#2935]
## 🐛 Bug Report

Hi, it seems as if DatePicker is not respecting updated dates when selecting what month to show when opened.

In particular when I change the 'date' input through other means (eg a button click to set particular date) the DatePicker is still stuck on the inital date

## To Reproduce

Run the following code as a sample:

`
import { DatePicker } from "@dnb/eufemia";
import { useState, useEffect } from "react";

export default function App() {
  const [dt, set] = useState("2023-01-01");
  let i = 2023;
  useEffect(() => {
    window.setInterval(() => {
      i++;
      set("" + i + "-01-01");
    }, 5000);
  }, []);

  console.log("render", dt);
  return <DatePicker show_input={false} date={dt} show_cancel_button={true} />;
}
`

## Expected behavior

DatePicker should always respect the current value of 'date'

**Comment by vron** [comment]
That example simply uses a callback to every five seconds update the date input into DatePicker - but regardles - any time the DatePicker button is called it opens op showing January 2023 as the month to start from

**Comment by vron** [comment]
Did you manage to confirm this issue or am I using the component in the wrong way? Thx

**Comment by vron** [comment]
Hi @joakbjerk would you be able to confirm if this is intended to work and something that will be fixed or if we should look for another solution? Thanks

**Comment by joakbjerk** [comment]
Hi @vron sorry for the late reply! 🙏 Did some quick testing right now, and it does seem like a bug. I'll look into if its a quick and easy fix right now 🔎

**Comment by vron** [comment]
Thanks :-)

**Comment by joakbjerk** [comment]
@vron You could check out [this pr](https://github.com/dnbexperience/eufemia/pull/3112) and double check that it actually fixes the thing you wanted, or if I misunderstood something 😄

**Comment by vron** [comment]
@tujoworker I'm trying to use this but struggling to (using npm) use this feature when there is no release including this fix, 

e.g. using:

    "dependencies": {
        "@dnb/eufemia": "https://github.com/dnbexperience/eufemia.git#main",
        
Does not work (I assume since eufemia is not in the root package) - any tips / best practices on how to depend on a particular commit for eufemia?

**Comment by tujoworker** [comment]
I dont think this fix is released. We will release it tomorrow 👍
