### ISSUE TITLE
DatePicker: aria help texts for selected date is not working

### ISSUE THREAD

**Issue by joakbjerk** [dnbexperience/eufemia#2949]
## 🐛 Bug Report

The aria support text that is suppose to tell which date is selected is empty.

<img width="1494" alt="Screenshot 2023-11-30 at 15 07 07" src="https://github.com/dnbexperience/eufemia/assets/25927156/fe371973-9009-4420-92d6-589131d359db">

This issue lies here:

<img width="522" alt="Screenshot 2023-11-30 at 15 13 03" src="https://github.com/dnbexperience/eufemia/assets/25927156/45bea885-0dcc-463c-a50c-db4bf5c68f81">

This function relies on the `startDate` and `endDate` states, which is never set anywhere inside the `DatePicker` component itself, leading to the dates always being `undefined`, meaning there is no dates to work with 

## To Reproduce

Select a date, and double the the text content inside `dnb-sr-only` `<p>` element, to see that it's empty

## Expected behavior

The aria support should be set and based on the selected date.

**Comment by langz** [comment]
Thank you 🙇
