### ISSUE TITLE
feat(Field.PostalCodeAndCity): Possibility to only use post code field

### ISSUE THREAD

**Issue by langz** [dnbexperience/eufemia#2975]
## 🚀 Feature Proposal

In my experience, when buying good or registering to a website, I often only enter the postnummer. As the poststed is given by the postnummer. So should we perhaps provide just the postal code field of the `Field.PostalCodeAndCity` component?

## Example

<img width="127" alt="image" src="https://github.com/dnbexperience/eufemia/assets/1359205/2f29817b-08ba-45e8-beb6-141da929fd6b">

**Comment by joakbjerk** [comment]
I'll start on this one 👍

**Comment by joakbjerk** [comment]
Did we conclude with closing this issue? @tujoworker

**Comment by tujoworker** [comment]
Yes, for now at lest.
