### ISSUE TITLE
bug(Field.Phonenumber): phone number label does not activate/focus the phone number field in certain scenarios

### ISSUE THREAD

**Issue by langz** [dnbexperience/eufemia#2977]
## 🐛 Bug Report

`<Field.PhoneNumber />`'s phone number label is sometimes difficult/impossible to click(making it not as easy as it should be to navigate to the phonenumber field). This only happens in certain scenarios.

Here's two videos of the issue:
In the first video, I remove all data in country code and search for "a" then click the first item. I then have to click the label "Mobilnummer" twice to be able to activate focus it.

https://github.com/dnbexperience/eufemia/assets/1359205/bc91830d-4db6-40aa-8cfd-1003adbcf3d2

In the second video, I just select a random item in the list of country code. I then have to click the label "Mobilnummer" twice to be able to activate focus it.

https://github.com/dnbexperience/eufemia/assets/1359205/5b7fd200-6668-4ee6-b03e-2f65673ffd11

## To Reproduce
This CSB is using `main` branch as of today, 06.12.2023.
https://codesandbox.io/p/sandbox/eufemia-starter-forked-yntt55?file=%2Fsrc%2FApp.tsx%3A2%2C44

Steps for video/scenario 1:
- Select all and remove the data in country code field.
- Type `"a"` and select the first/top item.
- Try to click the label of the "Mobilnummer"/phone number(You'll have to click twice to activate/focus the phone number field).

Steps for video/scenario 2:
- Click in the country code field.
- Select a random item form the country code list.
- Try to click the label of the "Mobilnummer"/phone number(You'll have to click twice to activate/focus the phone number field).

## Expected behaviour

I would expect it to work as the Autocomplete and the Input in the same [CSB](https://codesandbox.io/p/sandbox/eufemia-starter-forked-yntt55?file=%2Fsrc%2FApp.tsx%3A2%2C44)

In the video below, when using Autocomplete and Input, I only have to click the label of the Input once to activate/focus to the input:

https://github.com/dnbexperience/eufemia/assets/1359205/60ea26ba-e8de-4d1e-a2fa-7515ec420032

**Comment by joakbjerk** [comment]
solved by https://github.com/dnbexperience/eufemia/pull/3190
