### ISSUE TITLE
bug(Field.PostalCodeAndCity): clicking city label does not activate/focus the city field when postal code has error

### ISSUE THREAD

**Issue by langz** [dnbexperience/eufemia#2979]
## 🐛 Bug Report

Clicking `Field.PostalCodeAndCity`'s city label does not activate/focus the city field when postal code has error.

## To Reproduce
This CSB is using `main` branch as of today, 06.12.2023.
https://codesandbox.io/p/sandbox/eufemia-starter-forked-s9mzy2?file=%2Fsrc%2FApp.tsx

Steps:
- Type "1" in the postal code field.
- Click the label of the city field(the city field is not active/focused, and you have to click twice to make it happen)

Video:

https://github.com/dnbexperience/eufemia/assets/1359205/ab36f7ac-6527-4a47-b7cc-aa1351bb0f85

## Expected behaviour

I would expect the city field to be active/focused when clicking its label.

**Comment by snorrekim** [comment]
This seems to be an issue with all `<StringComponent>` and <NumberComponent>` fields (so also email, currency, etc.). After making an edit you can't click on it's own label, or on the label of another String or Number field next to it if they are part of the same Field widget (like phone number). 

But there's a lot of inconsistency in the behaviour, but it's consistent for String and Number vs their own label, so if that is fixe, we likely fix the others.

**Comment by snorrekim** [comment]
So this isn't really about error, or Field.PostalCodeAndCity, but about StringComponent and NumberComponent. Should we change the name of the issue?
