### ISSUE TITLE
bug(Field.Selection): clear option does not have a consistent behaviour

### ISSUE THREAD

**Issue by langz** [dnbexperience/eufemia#2980]
## 🐛 Bug Report

When clicking the "Fjern valgt verdi"-option in the f[ollowing example](https://eufemia.dnb.no/uilib/extensions/forms/base-fields/Selection/demos/#with-clear-button) it behaves differently from clicking it once, to twice:

https://github.com/dnbexperience/eufemia/assets/1359205/836bad1d-c95c-4371-a197-e83360bff908

First time clicking it, the dropdown/selection displays "Valgmeny": 
<img width="377" alt="Screenshot 2023-12-06 at 12 36 26" src="https://github.com/dnbexperience/eufemia/assets/1359205/80f5cf5f-da84-4a2f-a1ae-c757f982b779">

The second time clicking it, the dropdown/selection displays "Fjern valgt verdi":
<img width="368" alt="Screenshot 2023-12-06 at 12 36 35" src="https://github.com/dnbexperience/eufemia/assets/1359205/a3568261-8819-49b7-947a-b085d5c54f32">

## To Reproduce
This CSB is using `main` branch as of today, 06.12.2023.
https://codesandbox.io/p/sandbox/eufemia-starter-forked-4ct6wh?file=%2Fsrc%2FApp.tsx

**Comment by joakbjerk** [comment]
will be solved by https://github.com/dnbexperience/eufemia/pull/3327
