### ISSUE TITLE
bug(Field.Expiry): has wrong font color during disabled state

### ISSUE THREAD

**Issue by joakbjerk** [dnbexperience/eufemia#3022]
The font color should be grayish like the border, instead of the regular text colors as it has now

<img width="1196" alt="Screenshot 2023-12-07 at 14 29 36" src="https://github.com/dnbexperience/eufemia/assets/25927156/baa6b81c-f9db-4de1-b7b5-3ddc69c62eff">

**Comment by langz** [comment]
I created a CSB based, using latest on main as of today, and checked https://codesandbox.io/p/sandbox/eufemia-starter-forked-gn3cg7?file=%2Fsrc%2FApp.tsx%3A58%2C23
