### ISSUE TITLE
bug(Field.Selection): disabled does not work when variant is radio

### ISSUE THREAD

**Issue by langz** [dnbexperience/eufemia#3026]
## 🐛 Bug Report

In the light of the following two CSBs:
- [All Field.Components and variants with disabled and `without a value`](https://codesandbox.io/p/sandbox/eufemia-starter-forked-gn3cg7?file=%2Fsrc%2FApp.tsx%3A59%2C8-59%2C23)
- [All Field.Components and variants with disabled and `with a value`](https://codesandbox.io/p/sandbox/eufemia-starter-forked-6wry6m?file=%2Fsrc%2FApp.tsx)

It's observed that the following code does not result in a disabled input:
```
<Field.Selection
        path="/selection1"
        label="Selection radio disabled without value"
        disabled
        variant="radio"
      >
        <Field.Option value="foo" title="Foo!" />
        <Field.Option value="bar" title="Baar!" />
</Field.Selection>
```

Results in:
<img width="609" alt="image" src="https://github.com/dnbexperience/eufemia/assets/1359205/3f680d0a-51b0-43db-bbac-1f5be565d5ab">

## To Reproduce

[CSB with a reproduction](https://codesandbox.io/p/sandbox/eufemia-starter-forked-qgs4sm?file=%2Fsrc%2FApp.tsx%3A19%2C40)

**Comment by tujoworker** [comment]
This is fixed ([CSB](https://codesandbox.io/p/sandbox/eufemia-starter-forked-26ltng?file=%2Fpackage.json%3A17%2C79)) and part of main 👍
