### ISSUE TITLE
feat(Field.Option): support disabled property

### ISSUE THREAD

**Issue by langz** [dnbexperience/eufemia#3029]
## 🚀 Feature Proposal

In the light of the following two CSBs:
- [All Field.Components and variants with disabled and `without a value`](https://codesandbox.io/p/sandbox/eufemia-starter-forked-gn3cg7?file=%2Fsrc%2FApp.tsx%3A59%2C8-59%2C23)
- [All Field.Components and variants with disabled and `with a value`](https://codesandbox.io/p/sandbox/eufemia-starter-forked-6wry6m?file=%2Fsrc%2FApp.tsx)

It's observed that we don't support the `disabled` property for the `Field.Option` component.
In the following [CSB/examples](https://codesandbox.io/p/sandbox/eufemia-starter-forked-l7sc5t?file=%2Fsrc%2FApp.tsx%3A31%2C51), would it make sense to be able to disable one or more of the options, without disabling all?
Disabling all options could/should be done through the Field.Selection's disabled property.

Here's a screenshot of the CSB, where I would guess that it could make sense to disable one or multiple options:
<img width="461" alt="image" src="https://github.com/dnbexperience/eufemia/assets/1359205/5de3236d-d1cc-4108-bb83-674e2493fd51">

**Comment by joakbjerk** [comment]
partly solved by [bizzbazz](https://github.com/dnbexperience/eufemia/pull/3077). `Field.Option` inside a dropdown are still not possible to disable

**Comment by snorrekim** [comment]
As far as I can tell, Dropdown does not support disabling individual options, neither does DrawerList. So it wouldn't be expected in Forms either. So should we close this issue? @tujoworker

Or do we want to implement disabled for DrawerList and Dropdown?

**Comment by tujoworker** [comment]
Yes, seems to be fine now 💯
