### ISSUE TITLE
bug(Field.Selection): variant radio in Card with Flex.Horizontal has unwanted spacing

### ISSUE THREAD

**Issue by langz** [dnbexperience/eufemia#3037]
## 🐛 Bug Report

The following code:
```
      <Card>
        <Flex.Horizontal>
          <Field.Selection
            path="/selection2"
            label="Selection radio"
            variant="radio"
          >
            <Field.Option value="foo" title="Foo!" />
            <Field.Option value="bar" title="Baar!" />
          </Field.Selection>
        </Flex.Horizontal>
      </Card>
```
Results in more spacing between the label and the 1st option then expected:

<img width="759" alt="Screenshot 2023-12-10 at 12 21 11" src="https://github.com/dnbexperience/eufemia/assets/1359205/91f3916d-b55d-4840-9ee6-59d1c807bb4d">

## To Reproduce

[CSB](https://codesandbox.io/p/sandbox/eufemia-starter-forked-m54rzs?file=%2Fsrc%2FApp.tsx%3A27%2C27)

## Expected behavior

I would expect the two examples in the [CSB](https://codesandbox.io/p/sandbox/eufemia-starter-forked-m54rzs?file=%2Fsrc%2FApp.tsx%3A27%2C27) to have the same amount of margin/spacing between the label and the 1st radio button.

**Comment by snorrekim** [comment]
`<Flex>` uses css variables to set the gap, but those variables affect all `<Flex>` children. The Flex.Horizontal sets a variable that affects the Flex.Vertical used by the Field.Selection So we should probably make sure there is a reset of css variables for each `<Flex>`

**Comment by snorrekim** [comment]
This was inadvertently fixed in https://github.com/dnbexperience/eufemia/pull/3077 Moving the label outside the internal Flex.Container used by Radio.Group. Closed
