### ISSUE TITLE
bug(Field.PostalCodeAndCity): error does not add red borders to fields/inputs

### ISSUE THREAD

**Issue by langz** [dnbexperience/eufemia#3040]
## 🐛 Bug Report

In the light of the following two CSBs:
- [All Field.Components and variants with error and `without a value`](https://codesandbox.io/p/sandbox/eufemia-starter-forked-xgf9ww?file=%2Fsrc%2FApp.tsx%3A104%2C31)
- [All Field.Components and variants with error and `with a value`](https://codesandbox.io/p/sandbox/eufemia-starter-forked-ckv7qm?file=%2Fsrc%2FApp.tsx%3A120%2C31)

It's observed that the following code does not result in a red error border:
```
      <Field.PostalCodeAndCity
        postalCode={{
          path: '/postalCode',
        }}
        city={{
          path: '/city',
        }}
        error={new FormError('This is what is wrong...')}
      />
```

Results in:
<img width="334" alt="image" src="https://github.com/dnbexperience/eufemia/assets/1359205/92717901-63d3-4e5c-b7b3-6d5b9f3110d7">

**Comment by joakbjerk** [comment]
I'm suspecting it's caused by the same error as here https://github.com/dnbexperience/eufemia/issues/2968

**Comment by langz** [comment]
Closing this, as it's a duplicate of https://github.com/dnbexperience/eufemia/issues/2968
