### ISSUE TITLE
bug(Field.PhoneNumber): autofill of other country codes than 47

### ISSUE THREAD

**Issue by tujoworker** [dnbexperience/eufemia#3048]
When using Chrome, autofill will not change CC to e.g. +45 ...

**Comment by joakbjerk** [comment]
This seems to be working now, unless I'm testing it wrong 🙏

https://github.com/dnbexperience/eufemia/assets/25927156/7ecdcebd-9443-4ad7-a5b5-a4847690c3cb

**Comment by tujoworker** [comment]
Yes! When testing this, it surely looks good. Thanks for checking this out!
