### ISSUE TITLE
bug(Forms): using Form.SubHeading inside a card with stack doesn't display the stack border

### ISSUE THREAD

**Issue by langz** [dnbexperience/eufemia#3078]
## 🐛 Bug Report

Using `Form.SubHeading` inside a card with stack doesn't display the stack border between the elements in the card.

<img width="759" alt="image" src="https://github.com/dnbexperience/eufemia/assets/1359205/312bf801-850f-4c20-a922-9920c949cc2c">

I'm not 100% sure what we want the expected result to be here, but I find it strange that the "stack border" doesn't display in this scenario.

There's a lot of demos/examples in the docs that's written like this, and the "stack border" is not displayed. So it would be nice to know if it should be like this, or not 🙏 

## To Reproduce

Take a look in the following [CSB](https://codesandbox.io/p/sandbox/eufemia-starter-forked-jwp3gq?file=%2Fsrc%2FApp.tsx%3A27%2C21).
It includes a few different demos/examples, using Form and Card stack.

**Comment by joakbjerk** [comment]
It looks like you can fix this by wrapping the `Form.SubHeading` inside a `Flex.Item`. Not sure if this is the intended way for the user to fix this problem, or if it should work without the wrapping. On another note thought the `Form.SubHeading` itself do receive a grey underline beneath it by doing this, not sure if that is correct either, visually 🤔

[CSB](https://codesandbox.io/p/sandbox/eufemia-starter-forked-575c52?file=%2Fsrc%2FApp.tsx%3A30%2C14-30%2C29)

<img width="1476" alt="Screenshot 2023-12-15 at 10 04 23" src="https://github.com/dnbexperience/eufemia/assets/25927156/8a817853-bb0e-465a-a33e-5baa10bfa75f">

**Comment by langz** [comment]
> It looks like you can fix this by wrapping the `Form.SubHeading` inside a `Flex.Item`. Not sure if this is the intended way for the user to fix this problem, or if it should work without the wrapping. On another note thought the `Form.SubHeading` itself do receive a grey underline beneath it by doing this, not sure if that is correct either, visually 🤔
> 
> [CSB](https://codesandbox.io/p/sandbox/eufemia-starter-forked-575c52?file=%2Fsrc%2FApp.tsx%3A30%2C14-30%2C29)
> 
> <img alt="Screenshot 2023-12-15 at 10 04 23" width="1476" src="https://private-user-images.githubusercontent.com/25927156/290777415-8a817853-bb0e-465a-a33e-5baa10bfa75f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2NDA2ODAsIm5iZiI6MTcwMjY0MDM4MCwicGF0aCI6Ii8yNTkyNzE1Ni8yOTA3Nzc0MTUtOGE4MTc4NTMtYmIwZS00NjVhLWEzM2UtNWJhYTEwYmZhNzVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDExMzk0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmM2Y2Zjk0ZmFiOTQyZDdlZmUyYzM2YmE3MjhmMDE2ODE5MGQ3YzUyODE3MGY5OTdlNGNjMTMzZmQ1Y2ZjNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UlEEBhDIvDAZZ9QIlv-RqkUNlBZ_rfvvi2zEzHdJVGk">

A lot of question, and uncertainties :P 🤔

**Comment by joakbjerk** [comment]
Conclusion of discussion: Remove `stack` property from `Forms` demo examples that uses the `Card` component

**Comment by tujoworker** [comment]
Actually, we rather should make "space" the default separator and make the line "opt-in".

I have started on this change already.
