### ISSUE TITLE
bug(Forms): Submitting a Form removes the formatting of Fields

### ISSUE THREAD

**Issue by langz** [dnbexperience/eufemia#3080]
## 🐛 Bug Report

When submitting a Form, the formatting of fields like NationalIdentityNumber, BankAccountNumber, OrganizationNumber, Currency, PhoneNumber, and PostalCodeAndCity is lost.

Explained in a scenario:
- Organization number is formatted like `123 123 123`.
- User presses send/submit button.
- Formatting is lost and looks like `123123123`.

## To Reproduce

Press the send-button in the following [CSB](https://codesandbox.io/p/sandbox/eufemia-starter-forked-hkkfk6?file=%2Fsrc%2FApp.tsx%3A32%2C18)

Before pressing the send button:

<img width="756" alt="Screenshot 2023-12-13 at 16 04 27" src="https://github.com/dnbexperience/eufemia/assets/1359205/d4666aa8-f37a-472a-b848-d7b3e9b23812">

After pressing the send button:

<img width="756" alt="Screenshot 2023-12-13 at 16 04 40" src="https://github.com/dnbexperience/eufemia/assets/1359205/09d6e7a8-392c-460a-85eb-8f8309b39b15">

## Expected behavior

I would expect the fields to keep their formatting.

**Comment by joakbjerk** [comment]
The culprit seems to be the ` formElement?.reset?.()` that is being fired on submit

Not entirely sure about the best course of action to fix this 🙏

<img width="562" alt="Screenshot 2023-12-14 at 13 24 08" src="https://github.com/dnbexperience/eufemia/assets/25927156/83d8e8fd-d541-4d78-8da2-0082e8048ec6">

**Comment by tujoworker** [comment]
I work on a solution for this 👍

**Comment by tariknh** [comment]
Did this get fixed? I found that removing the cleanValue function, or removing cleanedValue in the result allowed formatting to stay on submit in InputMaskedHooks.js

**Comment by joakbjerk** [comment]
> Did this get fixed? I found that removing the cleanValue function, or removing cleanedValue in the result allowed formatting to stay on submit in InputMaskedHooks.js

No not yet, but a [fix](https://github.com/dnbexperience/eufemia/pull/3087) is in the making, but thank you for sharing your findings, that can probably help @tujoworker  even more 🙏

**Comment by tariknh** [comment]
Great, i suspect the issue might have something to do with the form inputs using the cleanedValue after submitting.

**Comment by langz** [comment]
Closed by https://github.com/dnbexperience/eufemia/pull/3087
