### ISSUE TITLE
bug(Upload): does not update state in StrictMode

### ISSUE THREAD

**Issue by joakbjerk** [dnbexperience/eufemia#3082]
## 🐛 Bug Report

Does not update state properly  `StrictMode`

Uploading a file in `StrictMode` results in no visible state change, while doing it outside of strict mode works as intended.

<img width="734" alt="Screenshot 2023-12-14 at 10 19 01" src="https://github.com/dnbexperience/eufemia/assets/25927156/4d590551-1ebe-4bca-93b8-85b379250e65">

Can be tested in [CSB](https://codesandbox.io/p/sandbox/young-water-k525cc?file=%2Fsrc%2FApp.tsx%3A6%2C7)

[Slack-discussion](https://dnb-it.slack.com/archives/CMXABCHEY/p1702539214106269)

**Comment by AadneRo** [comment]
Looks like this was fixed in [chore/upload-onchange-argument-type](https://github.com/dnbexperience/eufemia/pull/3113). Closing the issue
