### ISSUE TITLE
feat(Field.PostalCodeAndCity): Set max length to 4 in postal code field

### ISSUE THREAD

**Issue by langz** [dnbexperience/eufemia#3090]
## 🚀 Feature Proposal

Would it be nice to set the max length to 4 in the postal code field?
[As of today](https://eufemia-dnb-design-system-portal.vercel.app/uilib/extensions/forms/feature-fields/PostalCodeAndCity/#empty), we can enter more than 4 digits, but a norwegian postal number should only be 4 digits(no more, no less). We also state that in the description of [Field.PostalCodeAndCity](https://eufemia-dnb-design-system-portal.vercel.app/uilib/extensions/forms/feature-fields/PostalCodeAndCity/#description).

[Here's an example from Posten](https://www.posten.no/en/sending/domestic/letters/digital-stamp), on how they have a input field for postal code.

**Comment by joakbjerk** [comment]
I was just thinking, do we know if there will ever be an use case where the user could input a foreign postalcode? For example an uk postal code would be in this format `CR2 6XH `

**Comment by joakbjerk** [comment]
> I was just thinking, do we know if there will ever be an use case where the user could input a foreign postalcode? For example an UK postal code would be in this format `CR2 6XH`. Just a thought since we are supplying the user with foreign country codes for phone numbers, but that might be different.

We came to the conclusion of just focusing on norwegian postal codes for now 🙏
