### ISSUE TITLE
feat(Field.PhoneNumber): Display number keyboard in phone number field

### ISSUE THREAD

**Issue by langz** [dnbexperience/eufemia#3092]
## 🚀 Feature Proposal

Would it be nice to show the number input in keyboard on a mobile phone for the mobile phone field in Field.PhoneNumber?

[As of today](https://eufemia-dnb-design-system-portal.vercel.app/uilib/extensions/forms/feature-fields/PhoneNumber/#empty), when opening/focusing the postal code field, it shows the "regular keyboard", and then I as a user will have to change to numbers in the keyboard:
![PhoneNumber  Eufemia](https://github.com/dnbexperience/eufemia/assets/1359205/1f1feba8-68ff-4004-90fd-c72622430afc)

[Here's an example from Posten where I guess they use type="tel"](https://id.posten.no/login/4yc4uqbaqhwp5z2c0wsq9kre0qqin5ymfng6w86ihokmvl689n)(If link doesn't work, go to [posten](https://www.posten.no/) and press "Min side" in the top right corner), on how they have a input field for phone number on mobile:
![Postenid](https://github.com/dnbexperience/eufemia/assets/1359205/2ca57f3a-2704-49b0-9bdb-76448b64b22f)

[Here's an example from Material UI](https://mui.com/material-ui/react-text-field/) where we at least get the numbers(1,2,3,4,5,6,7,8,9,0) as part of the keyboard:
![React Text Field component - Material UI](https://github.com/dnbexperience/eufemia/assets/1359205/2d6cd714-c5d7-49f3-b6fc-42329acbe015)

**Comment by joakbjerk** [comment]
fixed by https://github.com/dnbexperience/eufemia/pull/3152
