### ISSUE TITLE
bug(forms): Fields with formatting/spacing between characters/digits looks strange in Safari on mobilephone

### ISSUE THREAD

**Issue by langz** [dnbexperience/eufemia#3100]
To me, all these Fields who have formatting/spacing looks strange when using in Safari on mobile phone. The cursor doesn’t really mark the end of the input value, which I’m used to. 

This applies to all Forms components with «formatting»: bank account number, national identity number, phonenumber, organization number, etc. Here’s a few observations:

https://github.com/dnbexperience/eufemia/assets/1359205/7926f17e-8574-4ecd-934f-1edd1ad7e1c9

https://github.com/dnbexperience/eufemia/assets/1359205/1b898870-dcf7-416a-85fb-3a19fa2ff5b0

https://github.com/dnbexperience/eufemia/assets/1359205/e13c0b63-77e2-4ac7-922d-65f8700b64f0

**Comment by joakbjerk** [comment]
Solved by https://github.com/dnbexperience/eufemia/pull/3194
