### ISSUE TITLE
bug(Field.Selection dropdown): width is to wide in Safari mobile

### ISSUE THREAD

**Issue by langz** [dnbexperience/eufemia#3101]
Not sure if the issue is in the example/demo or in the actual component. Anyhow, the width of the component seems to wide on my iPhone in Safari:

![IMG_4959](https://github.com/dnbexperience/eufemia/assets/1359205/3d4fc6ac-e057-4238-a667-056a9b0b207b)

For reference, this is how our dropdown component and docs looks on Safari mobile:

![IMG_4964](https://github.com/dnbexperience/eufemia/assets/1359205/8634b0e8-0506-4442-b1a8-088ef1c86ed7)

https://eufemia.dnb.no/uilib/components/dropdown/demos/

**Comment by tariknh** [comment]
The menu is using --forms-field-width--large: 21rem; for mobile, deselecting it seems to fix it
![image](https://github.com/dnbexperience/eufemia/assets/112902780/0ed46a0c-d65e-4978-81bb-d7c66e2cc50d)
