### ISSUE TITLE
bug(Forms): Different amount of spacing between Field components. 

### ISSUE THREAD

**Issue by langz** [dnbexperience/eufemia#3102]
To me, when browsing the docs on iPhone in Safari, it seems like there’s different spacing between the Field components in a card demo/example here https://eufemia.dnb.no/uilib/layout/#flex-usage-in-forms

![IMG_4967](https://github.com/dnbexperience/eufemia/assets/1359205/19c28e40-78da-4adc-9849-b3fee7fa8c9e)

To me, it seems like the spacing is different between the fields e-post and landskode, compared to spacing between all other fields.

**Comment by tariknh** [comment]
Could this be because landskode is correlated to the mobilnummer input, as in the law of proximity ? https://lawsofux.com/law-of-proximity/

**Comment by snorrekim** [comment]
This just seems to be a media query rule for the all our basic input components. But in <Forms> we only add the original class for widgets (`.dnb-autocomplete` `.dnb-date-picker`, etc.), but not for simple fields (`.dnb-input` is not used in <Forms>). So the extra margin only happens with widgets.

**Comment by snorrekim** [comment]
To put it on other words: If the label is set on the `<FieldBlock>` component instead of the input component, then the media query will not work. This happens in the `<StringComponent>` and `<NumberComponent>` (maybe others?).

**Comment by snorrekim** [comment]
But the question is, do we want that extra margin on small screens or not?

**Comment by tariknh** [comment]
I think it’s supposed to happen, as a "block" has children/siblings that is correlated, therefore less margin
