### ISSUE TITLE
bug(Field.OrganizationNumber): input removes values to the right of the cursor

### ISSUE THREAD

**Issue by langz** [dnbexperience/eufemia#3119]
## 🐛 Bug Report

When entering values in the organization number field to the left of already existing values, the "already existing values" gets overwritten/deleted.

Video:

https://github.com/dnbexperience/eufemia/assets/1359205/94e7ffab-31e6-4943-9ddc-7de694b88a82

## To Reproduce

Go to the [following example in our docs](https://eufemia.dnb.no/uilib/extensions/forms/feature-fields/OrganizationNumber/#empty):
- Enter `111`
- Move cursor to start of the input field
- Enter `222222222`

Se the '111' values gets removed.

## Expected behavior

I expect it to behave as a regular input field with maxlength attribute, see the following [CSB](https://codesandbox.io/p/sandbox/eloquent-goldberg-8vr69r?file=%2Fsrc%2FApp.tsx%3A4%2C43), and video:

https://github.com/dnbexperience/eufemia/assets/1359205/1494abd6-bb34-4f57-a803-0c92195dedc0

**Comment by joakbjerk** [comment]
Did we conclude with this being the expected behavior for `InputMaksed` @tujoworker?

**Comment by joakbjerk** [comment]
As intended for now.
