### ISSUE TITLE
bug(Field.Number): strange behaviour when entering big/large numbers

### ISSUE THREAD

**Issue by langz** [dnbexperience/eufemia#3121]
## 🐛 Bug Report

When entering values in the number field, it suddenly changes values.

All I do is entering the value `8`, many times.

Video:

https://github.com/dnbexperience/eufemia/assets/1359205/316f7353-c854-4acf-b746-bb0863256780

## To Reproduce

Go to the [following example in our docs](https://eufemia.dnb.no/uilib/extensions/forms/base-fields/Number/demos/#empty):
- Enter `8` many many times
- Then just observe what happens after entering `8` for the 17th time(input changes from `88888888888888888` to `88888888888888900`) and 22th time pressing 8(input changes to `8,888888888888` and onChange returns `8.88888888888889e+21`).

## Expected behavior

I expect it to behave as a regular input field, see the following [CSB](https://codesandbox.io/p/sandbox/boring-sky-kvqgxv?file=%2Fsrc%2FApp.tsx), and video(left is input type `string` and right is input type `number`):

https://github.com/dnbexperience/eufemia/assets/1359205/52788f63-a4f1-44e6-82c0-d6f2788cfd2d

**Comment by joakbjerk** [comment]
solved by https://github.com/dnbexperience/eufemia/pull/3184
