### ISSUE TITLE
Incorrect display value when using `update()` to reset a `Field.Boolean`

### ISSUE THREAD

**Issue by andlbrei** [dnbexperience/eufemia#3314]
## 🐛 Bug Report

When using `update()` from `Form.useData` to set a form value, represented by a `Field.Boolean` with variant `buttons`, to `undefined` the display value of the field is incorrect and unpredictable.

## To Reproduce

https://codesandbox.io/p/sandbox/erratic-field-boolean-update-7nrmnv
![boolean_erratic](https://github.com/dnbexperience/eufemia/assets/5804544/fd4a7c43-d884-47a2-bd7a-d6d4aa27d030)

## Expected behavior

Expected the field to not be selected after setting the value to `undefined`.

## Run `npx envinfo`

Paste the results here:

```bash

  System:
    OS: macOS 14.3.1
    CPU: (12) arm64 Apple M3 Pro
    Memory: 211.41 MB / 36.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.4.0 - ~/.nvm/versions/node/v21.4.0/bin/node
    Yarn: 1.22.21 - ~/.nvm/versions/node/v21.4.0/bin/yarn
    npm: 10.2.4 - ~/.nvm/versions/node/v21.4.0/bin/npm
    pnpm: 8.15.1 - ~/.nvm/versions/node/v21.4.0/bin/pnpm
    bun: 1.0.25 - ~/.bun/bin/bun
  Managers:
    Homebrew: 4.1.24 - /opt/homebrew/bin/brew
    pip3: 21.2.4 - /usr/bin/pip3
    RubyGems: 3.0.3.1 - /usr/bin/gem
  Utilities:
    Make: 3.81 - /usr/bin/make
    GCC: 15.0.0 - /usr/bin/gcc
    Git: 2.43.0 - /opt/homebrew/bin/git
    Clang: 15.0.0 - /usr/bin/clang
    Curl: 8.4.0 - /usr/bin/curl
  Servers:
    Apache: 2.4.56 - /usr/sbin/apachectl
  IDEs:
    IntelliJ: 2023.3.3
    Vim: 9.0 - /usr/bin/vim
    Xcode: /undefined - /usr/bin/xcodebuild
  Languages:
    Bash: 3.2.57 - /bin/bash
    Java: 21.0.1 - /Users/andersbreilid/.sdkman/candidates/java/current/bin/javac
    Perl: 5.30.3 - /usr/bin/perl
    Python3: 3.9.6 - /usr/bin/python3
    Ruby: 2.6.10 - /usr/bin/ruby
  Databases:
    SQLite: 3.43.2 - /usr/bin/sqlite3
  Browsers:
    Edge: 121.0.2277.112
    Safari: 17.3.1
```

## Eufemia Version

10.20.0

**Comment by tujoworker** [comment]
Nice finding! And thank you for the good reprod. I found the origin and make a fix PR.

There was just a tiny thing. To reset you may use both of these methods, and not provide the whole object. 

```ts
update('/questions/isThisTrue', () => undefined)
// or
update('/questions', () => ({
  isThisTrue: undefined,
}))
```

**Comment by andlbrei** [comment]
> Nice finding! And thank you for the good reprod. I found the origin and make a fix PR.
> 
> There was just a tiny thing. To reset you may use both of these methods, and not provide the whole object.
> 
> ```ts
> update('/questions/isThisTrue', () => undefined)
> // or
> update('/questions', () => ({
>   isThisTrue: undefined,
> }))
> ```

Thanks for the fix!

The reason I reset it like that is because we are working on a flow that initialises the form with stored data.
After editing, the user is going to be able to reset the data of a question or section of questions if they want to, back to the initial values.

**Comment by tujoworker** [comment]
You may use then the `set` method:

```ts
const { set } = Form.useData('unique-id')
set(initialData)
```

**Comment by andlbrei** [comment]
All right. I guess it would be the same as setting it on the Form Handler?
```js
 <Form.Handler id="unique" data={initialData}>
```

**Comment by tujoworker** [comment]
Yes, if you ensure you re-render the component with a new object in a custom state. Here are all three ways.

```ts

const initialData = {
  questions: {
    isThisTrue: undefined,
  },
}
export function BooleanReset() {
  const { set, update, data: myData } = Form.useData('unique')
  console.dir('data', myData)

  const [data, setInitialData] = React.useState(initialData)

  return (
    <Form.Handler id="unique" data={data}>
      <Flex.Vertical>
        <Field.Boolean
          variant="buttons"
          path="/questions/isThisTrue"
          label="Is this true?"
        />
        <Value.Boolean
          path="/questions/isThisTrue"
          label="Is it?"
          showEmpty
        />
        <Button
          onClick={() => update('/questions/isThisTrue', () => undefined)}
        >
          Reset 1
        </Button>

        <Button onClick={() => set(initialData)}>Reset 2</Button>

        <Button onClick={() => setInitialData({ ...initialData })}>
          Reset 3
        </Button>
      </Flex.Vertical>
    </Form.Handler>
  )
}

```

**Comment by andlbrei** [comment]
Great, thanks!
