### ISSUE TITLE
Field.PhoneNumber scandinavia countries

### ISSUE THREAD

**Issue by oggez** [dnbexperience/eufemia#3516]
## To Reproduce

Go to https://eufemia.dnb.no/uilib/extensions/forms/feature-fields/PhoneNumber/#show-only-scandinavian-countries.

First type 123 or some numbers under Label text.
Then click Landskode search and see the result.

![image](https://github.com/dnbexperience/eufemia/assets/17780527/d102251b-1f5f-4ae4-8027-63bd1a0cdb5f)

## Expected behavior

Should be Danmark, Norge and Sverige?

![image](https://github.com/dnbexperience/eufemia/assets/17780527/9bbab680-f1e6-4cd7-9bc9-ead06a4c74dc)

## Eufemia Version

latest

**Comment by joakbjerk** [comment]
I'll look into this now ⭐️
