### ISSUE TITLE
Field.Composition does not render error message when using schema validation

### ISSUE THREAD

**Issue by andlbrei** [dnbexperience/eufemia#3554]
## 🐛 Bug Report

When using Field.Composition in a form which uses JSON Schema with Ajv for validation, error messages are not displayed for the Field.Composition fields.

## To Reproduce

See codesandbox:

https://codesandbox.io/p/sandbox/recursing-currying-dq9f77

Schema validation:

https://github.com/dnbexperience/eufemia/assets/5804544/1e6ded89-6884-4d10-9d90-aeb5c9b35070

vs

Field level validation:

https://github.com/dnbexperience/eufemia/assets/5804544/59485bad-d0a6-4c98-9ec6-0d588d9992e3

## Expected behavior

Error messages to be displayed on validation, either initial validation or unchanged validation if enabled, or on submit, when using schema validation.

## Run `npx envinfo`

Paste the results here:

```bash
  System:
    OS: macOS 14.4.1
    CPU: (12) arm64 Apple M3 Pro
    Memory: 33.77 MB / 36.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.6.2 - ~/.nvm/versions/node/v21.6.2/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v21.6.2/bin/npm
    pnpm: 8.15.7 - ~/.nvm/versions/node/v21.6.2/bin/pnpm
    bun: 1.0.25 - ~/.bun/bin/bun
  Managers:
    Cargo: 1.76.0 - ~/.cargo/bin/cargo
    Homebrew: 4.2.21 - /opt/homebrew/bin/brew
    pip3: 24.0 - /opt/homebrew/bin/pip3
    RubyGems: 3.0.3.1 - /usr/bin/gem
  Utilities:
    Make: 3.81 - /usr/bin/make
    GCC: 15.0.0 - /usr/bin/gcc
    Git: 2.43.0 - /opt/homebrew/bin/git
    Clang: 15.0.0 - /usr/bin/clang
    Curl: 8.4.0 - /usr/bin/curl
    OpenSSL: 3.2.1 - /opt/homebrew/bin/openssl
  Servers:
    Apache: 2.4.58 - /usr/sbin/apachectl
  Virtualization:
    Docker: 25.0.3 - /usr/local/bin/docker
    Docker Compose: 2.24.5 - /usr/local/bin/docker-compose
  IDEs:
    IntelliJ: 2023.3.6
    VSCode: 1.89.0 - /usr/local/bin/code
    Vim: 9.0 - /usr/bin/vim
    Xcode: /undefined - /usr/bin/xcodebuild
  Languages:
    Bash: 3.2.57 - /bin/bash
    Java: 21.0.1 - /usr/bin/javac
    Perl: 5.34.1 - /usr/bin/perl
    Python3: 3.12.3 - /opt/homebrew/bin/python3
    Ruby: 2.6.10 - /usr/bin/ruby
    Rust: 1.76.0 - /Users/andersbreilid/.cargo/bin/rustc
  Databases:
    SQLite: 3.43.2 - /usr/bin/sqlite3
  Browsers:
    Edge: 124.0.2478.97
    Safari: 17.4.1
```

## Eufemia Version

**Browser JS:** "10.30.2"

**Browser CSS:** "10.30.2"

**Node.js:** Eufemia version: 10.30.2

**Comment by tujoworker** [comment]
Thank you for the good reproduction ⭐
