### ISSUE TITLE
Reloading Form Step with useReactRouter causes setActiveIndex is not a function error

### ISSUE THREAD

**Issue by andlbrei** [dnbexperience/eufemia#3702]
## 🐛 Bug Report

Fast refresh/reloading a form step page that uses `Wizard.useReactRouter()` results in a `setActiveIndex is not a function` error.

First example from local development with the Nucleus setup (webpack). Here dev server refresh causes the error:

https://github.com/dnbexperience/eufemia/assets/5804544/e93ddadd-842a-45da-947d-44dfdb3a4091

Second example is from codesandbox where dev refresh does not cause an error, but doing an explicit refresh does.
There are also some weird sync issues with the step information and the current step:

https://github.com/dnbexperience/eufemia/assets/5804544/ab19a04e-2003-433f-9a82-4edc99a0c2cb

## To Reproduce

https://codesandbox.io/p/sandbox/vigilant-field-dkkzvp?file=%2Fsrc%2FForm.tsx%3A18%2C41

1. Go to a step
2. Make sure the URL updates to contain a step query parameter
3. Refresh the window (in codesandbox this means using the refresh icon in the sandbox, do not refresh the browser)

## Expected behavior

Refreshing a form page with "step routing" should have the user stay on the same step without any errors.

## Run `npx envinfo`

Paste the results here:

```bash
❯ npx envinfo

  System:
    OS: macOS 14.5
    CPU: (12) arm64 Apple M3 Pro
    Memory: 138.95 MB / 36.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.6.2 - ~/.nvm/versions/node/v21.6.2/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v21.6.2/bin/npm
    pnpm: 8.15.7 - ~/.nvm/versions/node/v21.6.2/bin/pnpm
    bun: 1.1.13 - ~/.bun/bin/bun
  Managers:
    Cargo: 1.76.0 - ~/.cargo/bin/cargo
    Homebrew: 4.3.2 - /opt/homebrew/bin/brew
    pip3: 24.0 - /opt/homebrew/bin/pip3
    RubyGems: 3.0.3.1 - /usr/bin/gem
  Utilities:
    Make: 3.81 - /usr/bin/make
    GCC: 15.0.0 - /usr/bin/gcc
    Git: 2.43.0 - /opt/homebrew/bin/git
    Clang: 15.0.0 - /usr/bin/clang
    Curl: 8.6.0 - /usr/bin/curl
    OpenSSL: 3.3.0 - /opt/homebrew/bin/openssl
  Servers:
    Apache: 2.4.58 - /usr/sbin/apachectl
  Virtualization:
    Docker: 25.0.3 - /usr/local/bin/docker
    Docker Compose: 2.24.5 - /usr/local/bin/docker-compose
  IDEs:
    IntelliJ: 2023.3.6
    VSCode: 1.90.0 - /usr/local/bin/code
    Vim: 9.0 - /usr/bin/vim
    Xcode: /undefined - /usr/bin/xcodebuild
  Languages:
    Bash: 3.2.57 - /bin/bash
    Java: 21.0.1 - /usr/bin/javac
    Perl: 5.34.1 - /usr/bin/perl
    Python3: 3.12.3 - /opt/homebrew/bin/python3
    Ruby: 2.6.10 - /usr/bin/ruby
    Rust: 1.76.0 - /Users/andersbreilid/.cargo/bin/rustc
  Databases:
    SQLite: 3.43.2 - /usr/bin/sqlite3
  Browsers:
    Edge: 125.0.2535.92
    Safari: 17.5
```

## Eufemia Version
**This is not a new bug. It was present before 1.35**

**Browser JS:** Type `Eufemia.version` in your browser console.
'10.35.0'

**Node.js:** Use import or require to find out what Eufemia version is imported:
Eufemia version: 10.35.0

**Comment by tujoworker** [comment]
Thank you for reporting and creating this good reprod ❤️ This will be fixed in the upcoming version going out in an hour or so.

**Comment by andlbrei** [comment]
Thanks for the quick fix!
