### ISSUE TITLE
Format dates when rendering with `Value.Date`

### ISSUE THREAD

**Issue by kimroen** [dnbexperience/eufemia#3711]
## 🚀 Feature Proposal

Support formatting dates before displaying when using `Value.Date`.

## Motivation

At the moment we can render dates using [`Value.Date`](https://eufemia.dnb.no/uilib/extensions/forms/Value/Date), and it'll get a nice label by default:

<img width="395" title="Screenshot showing a Value.Date field rendered from Eufemia's documentation (linked above)" src="https://github.com/dnbexperience/eufemia/assets/520420/3fc7c16d-1866-4afd-96a6-843ca4961bc1" />

However, that's about it. Besides the label, it will act just like `Value.String` and render what the value is set to.

When used with the `Field.Date` picker to select the values, you will end up with dates formatted with the "YYYY-MM-DD" format. This is then passed straight through the `Value.Date`, and and rendered like that.

<img width="629" title="A screenshot of a date picker with a selected date, followed by how the value component renders this date as described above" src="https://github.com/dnbexperience/eufemia/assets/520420/d3efee59-fde7-4d99-87da-e7a0045334fa" />

This doesn't match what the DNB guidelines say about rendering dates, which is that we should render with date, name of month and then year ("1. juli 2024"), or if there is little room then "dd.mm.yyyy".

Here's [a codesandbox](https://codesandbox.io/p/sandbox/eufemia-starter-0gcwo) with a `Field.Date` above and a `Value.Date` that renders what is selected.

Hopefully this would also help in guiding a screenreader in how to read the displayed date.

## Alternatives

Without this functionality, the alternative is to format the date manually before passing it to `Value.Date`. This can be done either by formatting it and passing it through `value`, or by using the `transformIn` property (shown in the codesandbox above).

The downsides with this are:

1. We leave it up to each developer to decide how to format a date
2. Screen reader support can be flaky
3. We cannot directly integrate with the `Form.Handler` and `path` without writing extra code

<img width="614" title="A screenshot of a codesandbox example where a date is filled in using a date picker, and then the date is rendered twice below—once as default and once formatted as desired" src="https://github.com/dnbexperience/eufemia/assets/520420/f2a6d4bf-a7b9-4d6e-8778-fa0f88da1398" />

## Example

I'm not sure what a good API would look like, but maybe the `Value.Date` component could have some default formatting functionality, and optionally allow overriding. If there is some precedence for this in Eufemia, then we should probably follow that.

Ideally, if you just render a `Value.Date` and specify a `path`, then the selected date would be rendered according to DNBs date guidelines without any further work.

We could optionally allow somehow specifying how long we need the date to be so it can work in more space-constrained scenarios (for instance as part of a Composition).

Thanks!

**Comment by tujoworker** [comment]
The default formatting will be supported in the next version. Thank you so much for the good issue description.
