### ISSUE TITLE
DNB won't login on firefox 

### ISSUE THREAD

**Issue by wohoo111** [dnbexperience/eufemia#3788]
DNB has stopped working on firefox browser if I choose login through the bankID app. It says communication error. Tried with firefox with all addons disabled. Please fix.

**Comment by johanneslarsson** [comment]
I think the current workaround is to

1. Open Settings
2. Search for `cookie` at find in settings
3. Click `Manage Exceptions...`
4. Add `https://dnb.no`
5. Now you should be able to login with BankID
