### ISSUE TITLE
Iterate validation bypass

### ISSUE THREAD

**Issue by andlbrei** [dnbexperience/eufemia#4046]
## 🐛 Bug Report

When trying to add an invalid object to an iterate array, the object seems to be added while invalid. It seems to go from `PushContainer` to `EditContainer`.
Then, after typing something, the `ViewContainer` becomes active even though the object is invalid.

https://github.com/user-attachments/assets/6fd72f77-3dcf-4b19-852a-02f2975b6dfe

## To Reproduce

https://codesandbox.io/p/sandbox/iterate-validation-dwlkl3

## Expected behavior

I expect validation error messages to be displayed when trying to add an invalid object to an iterate array.
I expect the object not to be added when invalid after typing in one of the fields.

## Eufemia Version
10.51.1

**Comment by tujoworker** [comment]
The fields inside `MyNewItemForm` do not have `required`. Is that on purpose?

**Comment by tujoworker** [comment]
The `Iterate.PushContainer` does actually not support a `schema` as of today.

**Comment by tujoworker** [comment]
btw. the CSB uses a different version, not the latest. But that does not effect showing the issue.

Now, in v10.51.1 the default data from the `PushContainer` was `null`, which is falsy, and therefore the `EditContainer` opens:
<img width="163" alt="Screenshot 2024-10-06 at 21 39 36" src="https://github.com/user-attachments/assets/7e11639c-9094-4ffd-be0e-6a3282de5edc">

In the next version, we needed to change it from `null` to an empty object `{}`. So there it will go to a `ViewContainer`. 

<img width="327" alt="Screenshot 2024-10-06 at 21 43 41" src="https://github.com/user-attachments/assets/c79a332b-dd52-4f8c-a4bb-4e3f70c06650">

What do you think about that change?

**Comment by andlbrei** [comment]
Yea, I noticed that it acted differently when I tried it on the defaultValue PR branch build from last week.

So the issue here is that `PushContainer` is not using `schema` for validation, but `EditContainer` does?
The rest will be solved in the next release?

**Comment by andlbrei** [comment]
Hmm, ok.
That feels like internal logic that the consumer should not know about, but it's understandable with how the `PushContainer` is implemented with that kind of temporary path.
A bit unfortunate, but I guess it's not a big deal that the user goes from push-mode to edit-mode and then receives validation error messages.

**Comment by tujoworker** [comment]
> but it's understandable with how the PushContainer is implemented with that kind of temporary path.

Agree, its not ideal for a `schema`. Do you have any thoughts about how we could solve this?

Related to this subject, this PR #4076 did introduce a new prop `isolatedData` on the PushContainer, so its possible to put data for fields to consume with an ordinary `path`. 

Here is a [working example](https://eufemia-git-fix-push-container-keep-open-eufemia.vercel.app/uilib/extensions/forms/Iterate/PushContainer/#isolated-data) (simplified) on how this can be utilized.

**Comment by andlbrei** [comment]
> With this PR #4087, the `EditContainer` stays open during editing when it got force opened.
> 
> It also opens the `EditContainer` with an empty object. Does that make sense?

I think that makes sense, yes. I'll try it out.

> Related to this subject, this PR https://github.com/dnbexperience/eufemia/pull/4076 did introduce a new prop >isolatedData on the PushContainer, so its possible to put data for fields to consume with an ordinary path.

That looks interesting. I will try and change our implementation to use it, and let you know.

**Comment by andlbrei** [comment]
I tried both, and it seems to work fine 👍 
Regarding #4087 it might be nice to get validation messages when it adds the invalid object, but I don't think it's a big deal. I hope most users actually add something to those fields before adding... 😅 

I have some thoughts on #4076 .
The way I did it before was obviously a hack, and kind of messy.
The new way of doing it is definitely better, but might not be very intuitive.
I think what is a bit complicated is the fact that we are using a `path` in the `Selection` component to handle the selection of persons, which implies that we have a field in the form that will end up storing some data in the form.
It doesn't happen of course, since we are in the `Iterate` context here, which was why the hack worked.
But it's a bit confusing, or at least not intuitive.
I have no idea what to do about it, but if you happen to have an idea on some kind of "integrated form value that is not actually stored in the form data" concept, then it might be interesting to rename/rework the way this logic works so we don't use the `path` keyword for something that is not supposed to be stored.
This might relate to #4072 and buttons that needs to be pressed and stored, or even confirmation checkboxes ("I confirm that I have understood bla bla") where Eufemia Forms might need to know that the user has acted on these required actions, but not store the values in the form.

**Comment by tujoworker** [comment]
I think, its fine to put control/management paths into the data. We have several ways to filter them out, if needed. Can that work for you?

**Comment by andlbrei** [comment]
I'd be interested to see. I can always filter them out before sending it to the backend, so it's not a big problem either way.
I'm thinking more about how intuitive it is to use the correct pieces of functionality to solve a problem. But I guess that some things are just complicated, and we need to look at examples to see how to do it regardless with the "tools" that are available.
