### ISSUE TITLE
Add support for IE11

### ISSUE THREAD

**Issue by mlundela** [dnbexperience/eufemia#41]
## 🐛 Bug Report

Styles and font are wrong in IE11.

## To Reproduce

Open https://dnbexperience.github.io/eufemia/uilib/typography in IE11

## Expected behavior

Styles and fonts should work in IE11.

**Comment by tujoworker** [comment]
Hi @mlundela - thanks for the report. Yeah, an IE defender is on the roadmap. Still some other parts to prioritize right now. Can I chat with You on Slack?

**Comment by mlundela** [comment]
Sure, lets talk on monday :)

4. jan. 2019 20:13 skrev "Tobias Høegh" <notifications@github.com>:

Hi @mlundela <https://github.com/mlundela> - thanks for the report. Yeah,
an IE defender is on the roadmap. Still some other parts to prioritize
right now. Can I chat with You on Slack?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/dnbexperience/eufemia/issues/41#issuecomment-451539537>,
or mute the thread

**Comment by tujoworker** [comment]
This is fixed in [this version](https://github.com/dnbexperience/eufemia/releases/tag/v1.19.0)
