### ISSUE TITLE
Unhandled runtime error with FormLabel.tsx

### ISSUE THREAD

**Issue by Monkeyboyen** [dnbexperience/eufemia#4352]
Works in Eufemia package 10.53.0, updated to 10.57.1 and then I get a error.

Using Formset with Formrows and FormLabel as Label to populate form I get the following error :

![Screenshot 2024-12-02 141636](https://github.com/user-attachments/assets/329a91f8-7f14-4997-9771-4083823c8c38)

**Comment by langz** [comment]
Thanks so much for reporting 🙇 
I've tried making a [CSB](https://codesandbox.io/p/sandbox/inspiring-framework-n7ptzt) to reproduce this error, but have not been able to get it right yet.
Do you see anything I'm missing in the code, to be able to reproduce it?

Further, I believe the error is related to the changes done in https://github.com/dnbexperience/eufemia/pull/4282, more specifically the following line https://github.com/dnbexperience/eufemia/blob/85445b484f3b7eb85c07f4e396c9514a80275055/packages/dnb-eufemia/src/components/form-label/FormLabel.tsx#L181

**Comment by langz** [comment]
@Monkeyboyen, I think and hope we were able to fix it as part of https://github.com/dnbexperience/eufemia/pull/4354
But we never really managed to reproduce the error you reported.
Could you share some more of the code you've ran which resulted in the error?

Thanks 🙇

**Comment by Monkeyboyen** [comment]
@langz Hi, tested it now with 10.59.0 and its working as intended :)
