### ISSUE TITLE
Extend <Field.Upload /> with `onFileDownload` handler

### ISSUE THREAD

**Issue by torryt** [dnbexperience/eufemia#4355]
## 🚀 Feature Proposal

Extend the [<Field.Upload />](https://eufemia.dnb.no/uilib/extensions/forms/feature-fields/more-fields/Upload/) with a `onFileDownload` handler so that the full file can be downloaded on demand instead of pre-loaded in the form data.

## Motivation
The [<Field.Upload />](https://eufemia.dnb.no/uilib/extensions/forms/feature-fields/more-fields/Upload/) component expects input as an array containing the full [File](https://developer.mozilla.org/en-US/docs/Web/API/File) object. This means that when we preload a large form with several steps, and possibly several `<Field.Upload />` components, we also have to load all the files already uploaded in the form and preload them into the form state, which can significantly delay the first page load.

## Example
```tsx
async function onFileDownload(fileId: string): Promise<Blob> {
  const response = await getFileFromServer(fileId);

  return await response.blob();
}

....

<Field.Upload
  onFileDownload={onFileDownload}
/>
```

`onFileDownload` expects an async function that returns a file blob. When the function is provided, it overrides the default behavior of the file link and downloads from server instead of downloading the File object in the form state.

## Pitch

Reduces initial load time of forms with large files or many files and reduce unnecessary loading of documents that will probably not be downloaded.

**Comment by langz** [comment]
Thanks for the detailed feature request, @torryt 🚀 

I like the idea of a `onFileDownload` event or so, to download a given file from the server with a api request, and can definitely see the need for this.

I'll have to look more into how this works as of today.

I just took a quick search in the codebase, and as of today the code in Eufemia use multiple "file" properties, like `name`, `size`, `lastModified`, `id`, `type`, etc. Not sure what would happen if we don't provide these before the user clicks the link.

**Comment by langz** [comment]
I think this feature request is solved with the following PRs which is included in [v10.60.0](https://github.com/dnbexperience/eufemia/releases/tag/v10.60.0) of Eufemia:
- https://github.com/dnbexperience/eufemia/pull/4370
- https://github.com/dnbexperience/eufemia/pull/4369
- https://github.com/dnbexperience/eufemia/pull/4367

Please report back, and reopen the feature request if you find anything missing @torryt 🙇

**Comment by torryt** [comment]
This works just as expected @langz . Thank you very much! 💯 🙏

**Comment by langz** [comment]
> This works just as expected @langz . Thank you very much! 💯 🙏
> 
> 

Great, thanks🤗
I have a small improvement/fix for when chaining multiple of these asynchronous upload events. 

https://github.com/dnbexperience/eufemia/pull/4378
