### ISSUE TITLE
`<File.Upload />` infinite render loop when using `transformIn` property

### ISSUE THREAD

**Issue by torryt** [dnbexperience/eufemia#4366]
## 🐛 Bug Report

Using the `transformIn` in the `<File.Upload />` component cause an infinite render loop and the entire page will crash. 

## To Reproduce

https://codesandbox.io/p/sandbox/field-upload-infinite-render-loop-using-transformin-9gl7zy

## Expected behavior

For context, we are trying to map the `UploadValue` object from the `<File.Upload />` component to and from the following form state object:

```typescript
interface DocumentMetadata {
  id: string
  fileName: string
}
```

## Run `npx envinfo`

```bash
  System:
    OS: macOS 15.1.1
    CPU: (11) arm64 Apple M3 Pro
    Memory: 63.55 MB / 18.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.15.0 - ~/.nvm/versions/node/v20.15.0/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v20.15.0/bin/yarn
    npm: 10.7.0 - ~/.nvm/versions/node/v20.15.0/bin/npm
    pnpm: 9.14.2 - ~/.nvm/versions/node/v20.15.0/bin/pnpm
  Managers:
    Homebrew: 4.4.8 - /opt/homebrew/bin/brew
    pip3: 24.2 - ~/miniconda3/bin/pip3
    RubyGems: 3.0.3.1 - /usr/bin/gem
  Utilities:
    Make: 3.81 - /usr/bin/make
    GCC: 16.0.0 - /usr/bin/gcc
    Git: 2.45.1 - /opt/homebrew/bin/git
    Clang: 16.0.0 - /usr/bin/clang
    Curl: 8.7.1 - /usr/bin/curl
    OpenSSL: 3.0.15 - /Users/torrytufteland/miniconda3/bin/openssl
  Servers:
    Apache: 2.4.62 - /usr/sbin/apachectl
  Virtualization:
    Docker: 27.3.1 - /usr/local/bin/docker
    Docker Compose: 2.30.3 - /usr/local/bin/docker-compose
  IDEs:
    IntelliJ: 2024.2.3
    VSCode: 1.95.3 - /usr/local/bin/code
    Vim: 9.0 - /usr/bin/vim
    Xcode: /undefined - /usr/bin/xcodebuild
  Languages:
    Bash: 3.2.57 - /bin/bash
    Java: 21.0.4 - /Users/torrytufteland/.sdkman/candidates/java/current/bin/javac
    Perl: 5.34.1 - /usr/bin/perl
    Python: 3.12.7 - /Users/torrytufteland/miniconda3/bin/python
    Python3: 3.12.7 - /Users/torrytufteland/miniconda3/bin/python3
    Ruby: 2.6.10 - /usr/bin/ruby
  Databases:
    SQLite: 3.45.3 - /Users/torrytufteland/miniconda3/bin/sqlite3
  Browsers:
    Chrome: 131.0.6778.109
    Edge: 131.0.2903.86
    Safari: 18.1.1
```

## Eufemia Version

10.59.0

**Comment by tujoworker** [comment]
I wasn’t able to find a solution, and here’s why:

1. The field will receive the value either from the value/defaultValue prop or from the data context. It will run `transformIn`. It will then also try to set its value to the data context, if it not exists. But because it's an array, we can't compare it properly.  
2. The data context receives the new value.  
3. To sync this "path" with other fields or values that depend on it, a rerender is required. Rerenders only happen when the value has changed.
5. Because a new array instance is considered a new value, this triggers a rerender.  
6. During the data context rerender (Form.Handler), the field checks if the value from the data context has changed. However, since `transformIn` needs to run again, it produces a new instance, making comparison "again" impossible. The field then tries to set the new value in the data context again, and the cycle repeats.

How can we deal with that problem?

My suggestion is to create a dedicated section in the docs for when dealing with objects/arrayz in transformer functions.

**Comment by torryt** [comment]
Sounds like a good solution @tujoworker 👍 Mutating the input instead of creating a new array works for us, and explaining it in the docs would help out future users of the transformer functions.

**Comment by torryt** [comment]
Yes, that's correct! We want to store an object `{ id, fileName }` in the data context. We don't need to store the file itself in state, since we have a custom `onFileClick` handler that use the `id` to download the file.

**Comment by tujoworker** [comment]
I have updated the [CSB](https://codesandbox.io/p/sandbox/eufemia-forms-value-upload-transform-4hfr88) with the new version.

**Comment by torryt** [comment]
> If that's the only reason, I would recommend to not transform it. Because it (the File) should not be in the way when it is in the data context. Or is it?
Well, we submit the entire data context to the server, and the File object is potentially large. This will increase the request size, and makes the request object less readable.

> In the provided example, I actually provide a "file cache", just to restore the file again: https://eufemia-git-fix-forms-field-transform-in-out-instance-eufemia.vercel.app/uilib/extensions/forms/feature-fields/more-fields/Upload/#transformin-and-transformout
> 
> Let me know what do you think about it. Also, this PR enhances the docs about what "in" and "out" means when using these transformers.
I like these docs 👍 It is good that you named the variables "external" and "internal" to clarify the flow and source of data. 

Not sure about the purpose of the file cache though 🤔 How would this work if the user refresh the page, and the data is loaded from the `DocumentMetadata[]` object? There's no files present on the client side in that case.

**Comment by tujoworker** [comment]
> Well, we submit the entire data context to the server, and the File object is potentially large. This will increase the request size, and makes the request object less readable.

Yes, I totally understand this. And you can use that technique. You may else have a look on other techniques like [filterData](https://eufemia.dnb.no/uilib/extensions/forms/getting-started/#filter-data).

> Not sure about the purpose of the file cache though 🤔 How would this work if the user refresh the page, and the data is loaded from the DocumentMetadata[] object? There's no files present on the client side in that case.

Yeah, its only about the "possible" UX when a user clicks on the file to view it. It we would provide a "preview" of an image in the future.
