### ISSUE TITLE
Debounce method from Autocomplete returns undefined value

### ISSUE THREAD

**Issue by darkdubdeep** [dnbexperience/eufemia#625]
## 🐛 Bug Report

When you try to use the debounce method from the async Autocomplete component it returns an undefined value. Also, it seems like the debounce method return value immediately  even you will set 1500 as a timeout  parameter 

## To Reproduce

Go to this example https://eufemia.dnb.no/uilib/components/autocomplete#async-usage-dynamically-update-data-during-typing, open console, start typing. 

Video https://drive.google.com/file/d/1fT4lyy9TGmRQE7hVtFgrWlf0gdBCb0V7/view

BTW which helper uses the debounce method from Autocomplete component under the hood? I tried to discover the source code but found this 

![Anteckning 2020-09-03 105429](https://user-images.githubusercontent.com/30567626/92093679-e7240000-edd3-11ea-8e87-5b7beea1c71c.jpg)

## Expected behavior

Debounce method should return debounced value

**Comment by tujoworker** [comment]
Sorry for the late reply! You are right, the example code is wronge. The props and the delay should be reversed in order, like so:

```js
{ value },
250
```

The debounce function is here: https://github.com/dnbexperience/eufemia/blob/433528a1677226d5e466431de1d9604221711e62/packages/dnb-ui-lib/src/shared/helpers.js#L221

And here is it used by the Component: https://github.com/dnbexperience/eufemia/blob/433528a1677226d5e466431de1d9604221711e62/packages/dnb-ui-lib/src/components/autocomplete/Autocomplete.js#L894

Also, I will add it to the docs helper functions: https://eufemia.dnb.no/uilib/helpers/functions
