### ISSUE TITLE
Buggy dropdown list when used with tab

### ISSUE THREAD

**Issue by Eirmas** [dnbexperience/eufemia#720]
## 🐛 Bug Report

When using tab and enter/space to open the dropdown list menu it closes right after its been opened.

## To Reproduce

Use this component in a Vue project, importing it by using dnb.getComponents(Vue) as described in the docs.

## Expected behavior

The dropdown list should stay open after pressing enter/space

## Run `npx envinfo`

Paste the results here:

```bash

```

**Comment by tujoworker** [comment]
Hi Eirik! Thank You for getting in touch with the found issue. Could I challenge you to create a quick codesandbox.io example, demonstrating this?

**Comment by tujoworker** [comment]
The latest version should handle it better 👍
