### ISSUE TITLE
Is it correct that the TabsContentWrapper/TabsContent has tabIndex="0"?

### ISSUE THREAD

**Issue by langz** [dnbexperience/eufemia#779]
## 🐛 Bug Report

Is it correct that the TabsContentWrapper/TabsContent has tabIndex="0"?
https://github.com/dnbexperience/eufemia/blob/48877c5c62c6cba47db55d857f50851207a16fb0/packages/dnb-eufemia/src/components/tabs/TabsContentWrapper.js#L96

In certain scenarios, it "may" lead to an unwanted/extra tab(I think?).
Like when the TabsContent contains multiple buttons/cards (elements that can be focused, and where it participates in sequential keyboard navigation).

I am not sure, and haven't researched this with accessibility in mind.

## To Reproduce

https://codesandbox.io/s/new-silence-4qu50?file=/src/App.js

![image](https://user-images.githubusercontent.com/1359205/112493459-77329280-8d82-11eb-838d-f20a18f1e23a.png)

## Expected behavior

Should it tab directly to the 1st button, and not to the TabsContentWrapper/TabsContent?

**Comment by tujoworker** [comment]
Thanks for the good observation!  

Looking at the [WCAG examples](https://www.w3.org/TR/wai-aria-practices/examples/tabs/tabs-1/tabs.html) about the markup for tabs, I find this as a argument:

> Especially helpful if there are panels that do not contain a focusable element.

But I agree that it may rather be confusing than helpful – I have tested both VoiceOver and NVDA and can't find any advantages regarding to this. So I think we may actually revise that and go for `tabindex="-1"` with a click focus as an additional navigation helper.

**Comment by langz** [comment]
Thank you for taking the time to test this 👏
