### ISSUE TITLE
Improve warning for tertiary button without icon property

### ISSUE THREAD

**Issue by langz** [dnbexperience/eufemia#876]
## 🐛 Bug Report

This is just nitpicking, but it's actually a scenario I've experienced.

The following code `<Button text="Select" variant="tertiary"/>` results in Eufemia giving the following warning `"Eufemia: A Tertiary Button requires an icon. Please declare an icon to: null"`.

https://github.com/dnbexperience/eufemia/blob/cc23d02b71a659ed8beaeb9d15919bc89c5d436e/packages/dnb-eufemia/src/components/button/Button.js#L243

I interpreted this as "set the property icon to: null", therefore writing the following code `<Button text="Select" variant="tertiary" icon={null} />`, which will result in the same error again 😂 

## To Reproduce

https://codesandbox.io/s/new-silence-4qu50?file=/src/App.js
Then open the console.

## Expected behavior

Not exactly sure, but a clearer description of what to do in this scenario.

**Comment by tujoworker** [comment]
Thanks for the very good report 😍
Yes, true. The reason is, because a tertiary button needs an icon to be WCAG valid (it has no underline) – but the message should be improved.
