### ISSUE TITLE
Generate, and expose declaration files for Designs, ProductType, and CardType in @dnb/eufemia/extensions/payment-card/utils

### ISSUE THREAD

**Issue by langz** [dnbexperience/eufemia#935]
## 🚀 Feature Proposal

Generate, and expose declaration files for Designs, ProductType, and CardType of @dnb/eufemia/extensions/payment-card/utils.

I gave it a quick go, but I got a bit stuck, and didn't fully understand why PaymentCard.js's declaration file PaymentCard.d.ts ends up with `raw_data?: any;` given the following code: https://github.com/dnbexperience/eufemia/blob/9d572956a9ba8c281d21b1c736a4157a57de1f2c/packages/dnb-eufemia/src/extensions/payment-card/PaymentCard.js#L59

For Designs, ProductType, and CardType of @dnb/eufemia/extensions/payment-card/utils is there a way to "auto generate" these declaration files, or will these need to be manually created?

## Motivation

We are currently transitioning to TypeScript, using the tsconfig `noImplicitAny`, and this would be a welcoming feature.

## Example of an error message when importing Designs
`import Designs from '@dnb/eufemia/extensions/payment-card/utils/CardDesigns'`:

Could not find a declaration file for module '@dnb/eufemia/extensions/payment-card/utils/CardDesigns'. '/Users/anderslangseth/dev/dnb-web/node_modules/@dnb/eufemia/extensions/payment-card/utils/CardDesigns.js' implicitly has an 'any' type.

Try `npm i --save-dev @types/dnb__eufemia` if it exists or add a new declaration (.d.ts) file containing `declare module '@dnb/eufemia/extensions/payment-card/utils/CardDesigns';`ts(7016)
  
  
<img width="1001" alt="Screenshot 2021-08-07 at 22 51 56" src="https://user-images.githubusercontent.com/1359205/128613592-645dcaf3-172d-4041-9b46-8904774f9113.png">

## Pitch

I am not exactly sure if this is too much to offer from Eufemia or not.
I can probably fix it at the application side as well, but thought of adding this request, as Eufemia usually have a lot of nice declaration files for its modules 🙏

**Comment by tujoworker** [comment]
Thanks for the good issue description. The mentioned PropType was used twice and therefore set as a constant. The only little twist is, it needed to have the name `*PropType` in it. I'v updated the docs, they will show up once the release is out: https://eufemia.dnb.no/uilib/development/types#sharing-proptypes-between-components 

Speaking of release, it will go in to v9.9.6 or v9.10

**Comment by langz** [comment]
Thanks a lot @tujoworker, and welcome back from summer vacation 🌴 🌞
